/* Head-index buckets by hair colour, per gender -- GENERATED by
 * scripts/build_vv1_head_hair_buckets.py from the head preview bitmaps
 * (samples each variant's hair band, classifies Black/Brown/Red-Ginger/Blonde/
 * Other). Do not edit by hand; re-run the generator.
 *
 * Colour index: 0=Black, 1=Brown, 2=Red/Ginger, 3=Blonde, 4=Other.
 * vv1_head_pick(sex, colour, rng) returns a random head index from that
 * gender+colour bucket, or -1 if the bucket is empty (leave head unchanged).
 * sex: 1=male, 0=female.
 *
 * This placeholder ships EMPTY buckets so the DLL compiles before the generator
 * has run; every colour then returns -1 (no change) until Phase 4 bakes the
 * real buckets in. Random-by-gender does not use these tables.
 */
#ifndef VV1_HEAD_BUCKETS_H
#define VV1_HEAD_BUCKETS_H

#define VV_HAIR_COLOURS 5

static const unsigned char vv1_head_bucket_m[VV_HAIR_COLOURS][20] = {{0}};
static const unsigned char vv1_head_bucket_f[VV_HAIR_COLOURS][20] = {{0}};
static const int vv1_head_bucket_m_count[VV_HAIR_COLOURS] = {0, 0, 0, 0, 0};
static const int vv1_head_bucket_f_count[VV_HAIR_COLOURS] = {0, 0, 0, 0, 0};

/* colour is 0..4; sex 1=male else female. rng is an lcg-ish state the caller
 * advances. Returns a head index or -1 when the bucket is empty. */
static int vv1_head_pick(int sex, int colour, unsigned int *rng) {
    const unsigned char *bucket;
    int n;
    if (colour < 0 || colour >= VV_HAIR_COLOURS) {
        return -1;
    }
    if (sex) {
        bucket = vv1_head_bucket_m[colour];
        n = vv1_head_bucket_m_count[colour];
    } else {
        bucket = vv1_head_bucket_f[colour];
        n = vv1_head_bucket_f_count[colour];
    }
    if (n <= 0) {
        return -1;
    }
    *rng = *rng * 1664525u + 1013904223u;
    return (int)bucket[(*rng >> 16) % (unsigned int)n];
}

#endif /* VV1_HEAD_BUCKETS_H */
