/* Head-index buckets by hair colour, per gender -- GENERATED by
 * scripts/build_vv1_head_hair_buckets.py. Do not edit by hand.
 *
 * Colour index: 0=Black, 1=Brown, 2=Red/Ginger, 3=Blonde, 4=Other.
 * vv1_head_pick(sex, colour, rng) returns a random head index from that
 * gender+colour bucket, or -1 if empty. sex: 1=male, 0=female.
 */
#ifndef VV1_HEAD_BUCKETS_H
#define VV1_HEAD_BUCKETS_H

#define VV_HAIR_COLOURS 5

static const unsigned char vv1_head_bucket_m[VV_HAIR_COLOURS][20] = {
    { 8, 9, 11, 12, 13, 14, 15, 17 },
    { 0, 1, 2 },
    { 3, 5, 6, 10, 18 },
    { 7 },
    { 4, 16 },
};
static const unsigned char vv1_head_bucket_f[VV_HAIR_COLOURS][20] = {
    { 1, 4, 7, 9, 13, 16 },
    { 5 },
    { 8, 10, 14, 15 },
    { 2, 3, 12, 18 },
    { 0, 6, 11, 17, 19 },
};
static const int vv1_head_bucket_m_count[VV_HAIR_COLOURS] = { 8, 3, 5, 1, 2 };
static const int vv1_head_bucket_f_count[VV_HAIR_COLOURS] = { 6, 1, 4, 4, 5 };

static int vv1_head_pick(int sex, int colour, unsigned int *rng) {
    const unsigned char *bucket;
    int n;
    if (colour < 0 || colour >= VV_HAIR_COLOURS) {
        return -1;
    }
    if (sex) {
        bucket = vv1_head_bucket_m[colour];
        n = vv1_head_bucket_m_count[colour];
    } else {
        bucket = vv1_head_bucket_f[colour];
        n = vv1_head_bucket_f_count[colour];
    }
    if (n <= 0) {
        return -1;
    }
    *rng = *rng * 1664525u + 1013904223u;
    return (int)bucket[(*rng >> 16) % (unsigned int)n];
}

#endif /* VV1_HEAD_BUCKETS_H */
