/* Head-index buckets by hair colour, per gender -- GENERATED by
 * scripts/build_vv3_head_hair_buckets.py. Do not edit by hand.
 *
 * Colour index: 0=Black, 1=Brown, 2=Red/Ginger, 3=Blonde, 4=Other.
 * vv3_head_pick(sex, colour, rng) returns a random head index from that
 * gender+colour bucket, or -1 if empty. sex: 1=male, 0=female.
 *
 * Sampled from the YOUNG sheets: the old sheets are greyed by age and
 * would say nothing about the villager's hair colour.
 */
#ifndef VV3_HEAD_BUCKETS_H
#define VV3_HEAD_BUCKETS_H

#define VV3_HAIR_COLOURS 5
#define VV3_HEAD_COUNT_MAX 30

static const unsigned char vv3_head_bucket_m[VV3_HAIR_COLOURS][VV3_HEAD_COUNT_MAX] = {
    { 0, 1, 2, 3, 4, 5, 6, 7, 8 },
    { 9, 10, 11, 12, 16, 17, 18, 22, 23, 27 },
    { 13, 14, 15, 19, 20, 21 },
    { 24, 25, 26 },
    { 28, 29 },
};
static const unsigned char vv3_head_bucket_f[VV3_HAIR_COLOURS][VV3_HEAD_COUNT_MAX] = {
    { 0, 1, 2, 3, 4, 5, 6, 12 },
    { 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 23 },
    { 19, 20, 21, 22, 24, 25 },
    { 26, 27, 28 },
    { 18, 29 },
};
static const int vv3_head_bucket_m_count[VV3_HAIR_COLOURS] = { 9, 10, 6, 3, 2 };
static const int vv3_head_bucket_f_count[VV3_HAIR_COLOURS] = { 8, 11, 6, 3, 2 };

static int vv3_head_pick(int sex, int colour, unsigned int *rng) {
    const unsigned char *bucket;
    int n;
    if (colour < 0 || colour >= VV3_HAIR_COLOURS) {
        return -1;
    }
    bucket = sex ? vv3_head_bucket_m[colour] : vv3_head_bucket_f[colour];
    n = sex ? vv3_head_bucket_m_count[colour] : vv3_head_bucket_f_count[colour];
    if (n <= 0) {
        return -1;
    }
    *rng = (*rng * 1103515245u) + 12345u;
    return (int)bucket[(*rng >> 16) % (unsigned int)n];
}

#endif /* VV3_HEAD_BUCKETS_H */
