/* VVFP Story Upgrades -- the companion of the "Story / Cheat Upgrades" rows
   (all five games, default-off, requires the Origins upgrades).

   The owner: "Adds optional tools intended for custom stories, experiments,
   sandbox play, and cheats.  ...  When enabled, all Origins Upgrades cost 0
   Tech Points.  Also adds ... Pick Island Event -- Allows the player to
   directly choose which stock Island Event occurs instead of relying on
   random selection.  ...  Custom Island Event -- Allows the player to
   create and trigger a custom Island Event for storytelling, testing,
   sandbox play, or cheats."

   WHAT THIS COMPANION DOES.

   1. Free Origins upgrades.  Every place the Origins payload of the
      executable compares the tech-point balance with a price, deducts a
      price, refunds a price or shows a price is listed in story_tables.h
      (generated by scripts/build_story_cheat_upgrades_features.py, which
      checks every listed byte against the executable the patcher renders, in
      all three population modes).  VvfpStoryInstall verifies EVERY listed
      site first and writes nothing unless all of them hold exactly the bytes
      the Origins payload put there; then it writes the zero-cost bytes.  So
      the feature is all or nothing: a build whose Origins bytes differ gets
      no change at all, and the Origins companion keeps showing and charging
      the normal prices (it asks VvfpStoryActive before showing 0).
      A price of 0 keeps every lock: `cmp balance, 0; jb` never refuses, and
      every pending, capacity and "nothing to change" refusal still runs.

   2. Pick Island Event.  The player picks one of the game's own island
      events from a plain dialog.  The pick then makes the island event due
      exactly as the Origins "Island Event" purchase does (the same fields,
      so the same pending lock), and when the game's own scheduler fires that
      event, a detour at the point where the game has just chosen WHICH event
      to run replaces the random choice with the picked one -- and only if
      the game's own condition for that event holds at that moment.  The
      event is then created, shown and resolved by the game's own code, with
      its own random outcomes, choices and amounts; nothing about the event
      itself is emulated here.

   3. Custom Island Event (story_custom*.inc, story_c1..5.inc).  The player
      builds an event -- its title and description, village changes, new
      villagers, per-villager changes -- in plain dialogs; it is armed like a
      pick (the same lock: one pick or custom event at a time) and, when the
      game's own scheduler fires the island event, the game's own island
      event popup shows the custom title and description and the changes are
      made through each game's own routines.  Only what each game's own code
      was traced to support is offered in that game.

   4. Custom titles (story_titles.inc, native/shared/custom_titles.h): a
      villager's title replaced by the player's text in the villager panel,
      kept per save slot in a .dat file beside the saves.

   Installed at run time by VvfpStoryInstall(game) from the Origins
   companion (once it runs in the game process, outside DllMain).  The stock
   or Origins bytes at every site are verified first. */
#include <windows.h>
#include <string.h>
#include <intrin.h>
#include <stddef.h>

/* Each game's adapter table is declared before the functions that name it
   and defined after them (a tentative definition, standard C). */
#pragma warning(disable : 4132)

#include "story_tables.h"
#include "../shared/custom_titles.h"
#include "../shared/sidecar_io.h"
#include "../shared/save_folder.h"
#include "story_targets.h"
#include "story_custom.h"

enum {
    IDD_PICK = 301,
    IDC_PICK_LIST = 3001,
    IDC_PICK_DESC = 3002
};

#define PICK_TIMEOUT_MS (10u * 60u * 1000u)   /* an undelivered pick lapses after 10 minutes */
#define CAN_FIRE_TRIES 16                      /* see can_fire_with_retries */
#define TICK_MS 250u                           /* the custom titles' sweep, at most this often */

static HINSTANCE module_instance;
static int install_state[6];      /* 0 = not tried, 1 = active, -1 = refused */

/* The village a pick or a custom event was queued in: its save slot (as the
   Origins companion keys its own sidecars) and the reset generation, which
   VvfpStoryVillageReset advances whenever a tribe is deleted or started
   over.  A queued event is delivered only into that same village; loading
   another slot, Start Over or deleting a tribe discards it, so it can never
   replace another village's event or change its villagers. */
typedef struct {
    int slot;
    unsigned int generation;
} story_village;
static unsigned int story_village_generation;
static int story_current_slot(int game);

static story_village story_village_now(int game) {
    story_village v;
    v.slot = story_current_slot(game);
    v.generation = story_village_generation;
    return v;
}

static int story_village_is(int game, const story_village *v) {
    return v->slot == story_current_slot(game) && v->generation == story_village_generation;
}

/* The armed pick: the game's own index of the chosen event (-1 = none),
   when it was armed, and the table entry it came from. */
static int pick_slot = -1;
static int pick_game;
static DWORD pick_tick;
static const story_event *pick_event;
static story_village pick_village;
/* The outcome of the last pick, shown the next time the chooser opens when
   the game could not run it. */
static const story_event *last_failed_event;

#ifdef VVFP_TEST
/* Counters the tests read.  Compiled only into the TEST build. */
struct vvfp_story_stats {
    int delivered;      /* a picked or custom event replaced the game's own */
    int refused;        /* the picked event's own condition did not hold */
    int lapsed;         /* an armed pick or custom event was dropped as too old */
    int discarded;      /* an armed pick or custom event was dropped: another village */
};
__declspec(dllexport) struct vvfp_story_stats VvfpStoryStats = { 0 };
#define STORY_COUNT(field) (++VvfpStoryStats.field)
static DWORD test_tick;
#define STORY_TICK() (test_tick)
#else
#define STORY_COUNT(field) ((void)0)
#define STORY_TICK() (GetTickCount())
#endif

/* Defined with the Custom Island Event (story_custom.inc), used earlier. */
static int ce_pending(int game);
static void *c3_custom_object(void);
static void *c4_custom_object(void);
static void *c5_custom_object(void);
/* ---- Memory ---------------------------------------------------------------- */

static int mem_readable(unsigned int va, int length) {
    MEMORY_BASIC_INFORMATION info;
    const void *at = (const void *)(uintptr_t)va;
    if (VirtualQuery(at, &info, sizeof(info)) != sizeof(info) || info.State != MEM_COMMIT
        || (info.Protect & (PAGE_NOACCESS | PAGE_GUARD)) != 0) {
        return 0;
    }
    return (uintptr_t)at + (unsigned int)length
           <= (uintptr_t)info.BaseAddress + info.RegionSize;
}

static int mem_matches(unsigned int va, const unsigned char *bytes, int length) {
    if (!mem_readable(va, length)) {
        return 0;
    }
    return memcmp((const void *)(uintptr_t)va, bytes, (size_t)length) == 0;
}

static int mem_write(unsigned int va, const unsigned char *bytes, int length) {
    DWORD old;
    void *at = (void *)(uintptr_t)va;
    if (!VirtualProtect(at, (SIZE_T)length, PAGE_EXECUTE_READWRITE, &old)) {
        return 0;
    }
    memcpy(at, bytes, (size_t)length);
    VirtualProtect(at, (SIZE_T)length, old, &old);
    FlushInstructionCache(GetCurrentProcess(), at, (SIZE_T)length);
    return 1;
}

static unsigned int read_u32(unsigned int va) {
    return *(volatile unsigned int *)(uintptr_t)va;
}

/* The bytes a detour writes at its site: a jmp (or, for a call site, a call)
   to the stub, padded with nops. */
static void detour_bytes(const story_detour *d, unsigned char *out) {
    unsigned int rel = (unsigned int)((uintptr_t)d->stub - ((uintptr_t)d->va + 5));
    int i;
    out[0] = d->is_call ? 0xE8 : 0xE9;
    memcpy(out + 1, &rel, 4);
    for (i = 5; i < d->length; ++i) {
        out[i] = 0x90;
    }
}

/* ---- Per-game event code -------------------------------------------------- */

typedef char (__fastcall *can_fire_fn)(void *self, void *unused_edx);
typedef void *(__cdecl *getter_fn)(void);

/* The game's own condition for an event object (vtable slot 1, thiscall, no
   arguments).  Several conditions roll the game's random generator or pick
   the villager the event will be about (stored in the object), so a false
   answer can be random rather than final: it is asked a few times before the
   event is called impossible.  A true answer leaves the object exactly as
   the game's own selector would have left it before running the event. */
static int can_fire_with_retries(void *object) {
    int i;
    for (i = 0; i < CAN_FIRE_TRIES; ++i) {
        can_fire_fn can_fire = (can_fire_fn)(*(void ***)object)[1];
        if (can_fire(object, NULL)) {
            return 1;
        }
    }
    return 0;
}

/* An armed pick that the game has not run within PICK_TIMEOUT_MS is
   dropped (so a pick can never carry over into a village loaded much later);
   the next chooser says so.  Returns 1 when a pick was dropped. */
static int last_failed_lapsed;

static int drop_lapsed_pick(void) {
    if (pick_slot >= 0 && !story_village_is(pick_game, &pick_village)) {
        /* Another village: the pick was for the one the player left. */
        pick_slot = -1;
        STORY_COUNT(discarded);
        return 1;
    }
    if (pick_slot >= 0 && STORY_TICK() - pick_tick > PICK_TIMEOUT_MS) {
        pick_slot = -1;
        last_failed_event = pick_event;
        last_failed_lapsed = 1;
        STORY_COUNT(lapsed);
        return 1;
    }
    return 0;
}

/* Takes the armed pick for `game` (and clears it): the game's index of the
   event, or -1. */
static int take_pick(int game) {
    int slot;
    if (drop_lapsed_pick()) {
        return -1;
    }
    slot = pick_slot;
    if (slot < 0 || pick_game != game) {
        return -1;
    }
    pick_slot = -1;
    return slot;
}

/* For VV3, VV4 and VV5: the selector has just chosen `current`; return the
   index the selector should use.  `table` is the game's event-object array. */
static int choose_from_table(int game, unsigned int table, int current) {
    void *object;
    const story_event *event = pick_event;
    int slot = take_pick(game);
    if (slot < 0) {
        return current;
    }
    object = *(void **)(uintptr_t)(table + 4u * (unsigned int)slot);
    if (object != NULL && can_fire_with_retries(object)) {
        STORY_COUNT(delivered);
        last_failed_event = NULL;
        return slot;
    }
    STORY_COUNT(refused);
    last_failed_event = event;
    last_failed_lapsed = 0;
    return current;
}

/* The Secret City.  0x419BDB `mov edx, [esi*4 + 0x4B3C78]` is where the
   selector 0x419B30 has settled on `esi` (after its own random pick and its
   rescue override) and is about to build the event dialog.  A custom event
   armed for this game is presented here instead (story_c3.inc); otherwise
   an armed pick replaces the choice.

   The Origins Barrel of Babies delivers its barrel by calling the same
   selector with EVERY slot pointing at the barrel object (0x47B3E0); neither
   a pick nor a custom event is consumed there, because what would run is
   the barrel.  All slots equal is that state and never the game's own.

   Returns the object to present instead of the table's, or NULL (and the
   slot the selector should use in *slot). */
static void *__cdecl vv3_select(int *slot) {
    void *custom;
    if (read_u32(VV3_EVENT_TABLE + 4) == read_u32(VV3_EVENT_TABLE + 8)) {
        return NULL;
    }
    custom = c3_custom_object();
    if (custom != NULL) {
        return custom;
    }
    *slot = choose_from_table(3, VV3_EVENT_TABLE, *slot);
    return NULL;
}

/* pushad stores EDI, ESI, EBP, ESP, EBX, EDX, ECX, EAX from [esp] up, so the
   saved ESI is [esp+4] and the saved EAX [esp+0x1C]. */
__declspec(naked) static void vv3_stub(void) {
    __asm {
        pushad
        lea eax, [esp + 4]
        push eax
        call vv3_select
        add esp, 4
        mov dword ptr [esp + 0x1C], eax
        popad
        test eax, eax
        jnz custom
        mov edx, dword ptr [esi * 4 + 0x4B3C78]
        push 0x419BE2
        ret
    custom:
        mov edx, eax
        push 0x419BE2
        ret
    }
}

/* The Tree of Life.  0x4180F7 `mov eax, [esi*4 + 0x4CCA28]`: the selector
   0x418000 has settled on `esi` (after the random pick and the rescue
   override) and is about to present it.  The Origins Barrel delivers through
   0x418190 instead, which never passes here. */
static void *__cdecl vv4_select(int *slot) {
    void *custom = c4_custom_object();
    if (custom != NULL) {
        return custom;
    }
    *slot = choose_from_table(4, VV4_EVENT_TABLE, *slot);
    return NULL;
}

__declspec(naked) static void vv4_stub(void) {
    __asm {
        pushad
        lea eax, [esp + 4]
        push eax
        call vv4_select
        add esp, 4
        mov dword ptr [esp + 0x1C], eax
        popad
        test eax, eax
        jnz custom
        mov eax, dword ptr [esi * 4 + 0x4CCA28]
    custom:
        push 0x4180FE
        ret
    }
}

/* New Believers.  0x41895B `mov eax, [esi*4 + 0x4DC850]`: after the Origins
   selector stub (0x41890F, the purchased Barrel) and the stock Chutes Without
   Ladders override, so nothing later can replace the pick.  A purchased
   Barrel shares the Island Event lock, so it is never armed together with a
   custom event. */
static void *__cdecl vv5_select(int *slot) {
    void *custom = c5_custom_object();
    if (custom != NULL) {
        return custom;
    }
    *slot = choose_from_table(5, VV5_EVENT_TABLE, *slot);
    return NULL;
}

__declspec(naked) static void vv5_stub(void) {
    __asm {
        pushad
        lea eax, [esp + 4]
        push eax
        call vv5_select
        add esp, 4
        mov dword ptr [esp + 0x1C], eax
        popad
        test eax, eax
        jnz custom
        mov eax, dword ptr [esi * 4 + 0x4DC850]
    custom:
        push 0x418962
        ret
    }
}

/* Each game's clock (seconds), thiscall on the world object. */
typedef int (__fastcall *clock_fn)(void *self, void *unused_edx);

#include "story_vv1.inc"
#include "story_vv2.inc"

/* ---- Making the island event due ------------------------------------------ */

/* Each game: is an island event already on its way (the Island Event row's
   own lock), and make one due exactly as the Origins Island Event purchase
   does.  Returns 1 on success. */
static int vv3_island_pending(void) {
    return *(volatile unsigned char *)(uintptr_t)VV3_ISLAND_FLAG != 0;
}

static int vv3_arm(void) {
    void *manager = *(void **)(uintptr_t)VV3_MANAGER_GLOBAL;
    void (__fastcall *queue_arm_island)(void *, void *) =
        (void (__fastcall *)(void *, void *))(uintptr_t)VV3_QUEUE_ARM_ISLAND;
    if (manager == NULL) {
        return 0;
    }
    queue_arm_island(manager, NULL);   /* the Island Event purchase's own helper */
    return 1;
}

static int vv4_island_pending(void) {
    unsigned char *world = *(unsigned char **)(uintptr_t)VV4_WORLD_GLOBAL;
    unsigned int countdown;
    if (world == NULL) {
        return 1;
    }
    countdown = *(unsigned int *)(world + VV4_COUNTDOWN);
    if (*(volatile unsigned char *)(uintptr_t)VV4_ISLAND_TOKEN != 0
        && (countdown == read_u32(VV4_ISLAND_STAMP)
            || *(volatile unsigned char *)(uintptr_t)VV4_BARREL_ARMED != 0)) {
        return 1;
    }
    if (countdown == 0) {
        return 1;
    }
    return countdown - (unsigned int)((clock_fn)(uintptr_t)VV4_CLOCK)(world, NULL) <= 5u;
}

static int vv4_arm(void) {
    unsigned char *world = *(unsigned char **)(uintptr_t)VV4_WORLD_GLOBAL;
    unsigned int due;
    if (world == NULL) {
        return 0;
    }
    due = (unsigned int)((clock_fn)(uintptr_t)VV4_CLOCK)(world, NULL) + 5u;
    *(unsigned int *)(world + VV4_COUNTDOWN) = due;
    *(volatile unsigned char *)(uintptr_t)VV4_ISLAND_TOKEN = 1;
    *(volatile unsigned int *)(uintptr_t)VV4_ISLAND_STAMP = due;
    return 1;
}

static int vv5_island_pending(void) {
    return (read_u32(VV5_PURCHASE_FLAGS) & 0x3Cu) != 0;
}

static int vv5_arm(void) {
    unsigned char *world = *(unsigned char **)(uintptr_t)VV5_WORLD_GLOBAL;
    if (world == NULL) {
        return 0;
    }
    *(unsigned int *)(world + VV5_COUNTDOWN) = 0;
    *(volatile unsigned int *)(uintptr_t)VV5_PURCHASE_FLAGS |= 0x10u;
    return 1;
}

/* Whether the game's own condition for an event holds right now.  VV3-VV5:
   the event object's own condition, through the game's own event table
   (built by the game's own getter if no event has run yet this session). */
static int table_event_possible(unsigned int table, getter_fn getter, int slot) {
    void *object = *(void **)(uintptr_t)(table + 4u * (unsigned int)slot);
    if (object == NULL) {
        getter();
        object = *(void **)(uintptr_t)(table + 4u * (unsigned int)slot);
    }
    return object != NULL && can_fire_with_retries(object);
}

static int vv3_possible(const story_event *e) {
    return table_event_possible(VV3_EVENT_TABLE, (getter_fn)(uintptr_t)VV3_EVENT_GETTER, e->slot);
}

static int vv4_possible(const story_event *e) {
    return table_event_possible(VV4_EVENT_TABLE, (getter_fn)(uintptr_t)VV4_EVENT_GETTER, e->slot);
}

static int vv5_possible(const story_event *e) {
    return table_event_possible(VV5_EVENT_TABLE, (getter_fn)(uintptr_t)VV5_EVENT_GETTER, e->slot);
}

/* ---- Custom Island Event -------------------------------------------------- */

/* The record helpers the custom titles use (story_titles.inc), defined with
   the adapters below. */
static int story_record_count(int game);
static unsigned char *story_record(int game, int index);
static int story_record_index(int game, const unsigned char *record);
static int story_record_alive(int game, const unsigned char *record);
static unsigned int story_name_fingerprint(int game, const unsigned char *record);
static const char *titles_lookup(int game, const unsigned char *record);
static int titles_set(int game, int index, const char *text);

#include "story_common.inc"
#include "story_custom.inc"
#include "story_objects.inc"
#include "story_c1.inc"
#include "story_c2.inc"
#include "story_c3.inc"
#include "story_c4.inc"
#include "story_c5.inc"

static const ce_adapter *ce_adapter_for(int game) {
    switch (game) {
    case 1: return &C1_ADAPTER;
    case 2: return &C2_ADAPTER;
    case 3: return &C3_ADAPTER;
    case 4: return &C4_ADAPTER;
    case 5: return &C5_ADAPTER;
    default: return NULL;
    }
}

static int story_record_count(int game) {
    const ce_adapter *a = ce_adapter_for(game);
    return a != NULL ? a->record_count : 0;
}

static unsigned char *story_record(int game, int index) {
    const ce_adapter *a = ce_adapter_for(game);
    return a != NULL ? a->record(index) : NULL;
}

static int story_record_index(int game, const unsigned char *record) {
    const ce_adapter *a = ce_adapter_for(game);
    int i;
    if (a == NULL || record == NULL) {
        return -1;
    }
    for (i = 0; i < a->record_count; ++i) {
        if (a->record(i) == record) {
            return i;
        }
    }
    return -1;
}

static int story_record_alive(int game, const unsigned char *record) {
    const ce_adapter *a = ce_adapter_for(game);
    return a != NULL && record != NULL && a->listed(record);
}

static unsigned int story_name_fingerprint(int game, const unsigned char *record) {
    const ce_adapter *a = ce_adapter_for(game);
    return a != NULL ? ce_fingerprint(a, record) : 0;
}

#include "story_titles.inc"

/* ---- The per-game table ---------------------------------------------------- */

typedef struct {
    const story_write *writes;
    int write_count;
    const story_detour *detours;
    int detour_count;
    const story_detour *more_detours;   /* VV1 / VV2: the custom event's own sites */
    int more_detour_count;
    const story_event *events;
    int event_count;
    int (*possible)(const story_event *event);
    int (*island_pending)(void);
    int (*arm)(void);
} story_game;

/* The Custom Island Event's own sites follow each game's pick sites: its
   delivery (VV1 / VV2: the island event's chooser call; VV3-VV5: the pick
   site itself) and the villager panel's title (story_c*.inc). */
static story_detour vv1_custom_detours[] = {
    { 0x428777u, 5, VV1_CUSTOM_CHOOSE_BYTES, 1, (void *)c1_choose },
    { 0x41FD75u, 5, VV1_TITLE_SITE_BYTES, 0, (void *)c1_title_stub },
};
static story_detour vv2_custom_detours[] = {
    { 0x4349B2u, 5, VV2_CUSTOM_CHOOSE_BYTES, 1, (void *)c2_choose },
    { 0x429DE3u, 5, VV2_TITLE_SITE_BYTES, 1, (void *)c2_title },
};
static story_detour vv3_detours[] = {
    { VV3_PICK_SITE, 7, VV3_PICK_SITE_BYTES, 0, (void *)vv3_stub },
    { 0x468FC8u, 6, VV3_TITLE_SITE_BYTES, 0, (void *)c3_title_stub },
};
static story_detour vv4_detours[] = {
    { VV4_PICK_SITE, 7, VV4_PICK_SITE_BYTES, 0, (void *)vv4_stub },
    { 0x4404D9u, 5, VV4_TITLE_SITE_BYTES, 0, (void *)c4_title_stub },
};
static story_detour vv5_detours[] = {
    { VV5_PICK_SITE, 7, VV5_PICK_SITE_BYTES, 0, (void *)vv5_stub },
    { 0x44319Eu, 6, VV5_TITLE_SITE_BYTES, 0, (void *)c5_title_stub },
};

static const story_game GAMES[6] = {
    { 0 },
    { VV1_WRITES, VV1_WRITE_COUNT, vv1_detours, sizeof vv1_detours / sizeof vv1_detours[0],
      vv1_custom_detours, 2,
      VV1_EVENTS, VV1_EVENT_COUNT, vv1_possible, vv1_island_pending, vv1_arm },
    { VV2_WRITES, VV2_WRITE_COUNT, vv2_detours, sizeof vv2_detours / sizeof vv2_detours[0],
      vv2_custom_detours, 2,
      VV2_EVENTS, VV2_EVENT_COUNT, vv2_possible, vv2_island_pending, vv2_arm },
    { VV3_WRITES, VV3_WRITE_COUNT, vv3_detours, 2, NULL, 0,
      VV3_EVENTS, VV3_EVENT_COUNT, vv3_possible, vv3_island_pending, vv3_arm },
    { VV4_WRITES, VV4_WRITE_COUNT, vv4_detours, 2, NULL, 0,
      VV4_EVENTS, VV4_EVENT_COUNT, vv4_possible, vv4_island_pending, vv4_arm },
    { VV5_WRITES, VV5_WRITE_COUNT, vv5_detours, 2, NULL, 0,
      VV5_EVENTS, VV5_EVENT_COUNT, vv5_possible, vv5_island_pending, vv5_arm },
};

/* ---- Installing ------------------------------------------------------------ */

/* The detour `index` of this game: its pick sites, then the custom
   event's own. */
static int game_detour_count(const story_game *g) {
    return g->detour_count + g->more_detour_count;
}

static const story_detour *game_detour(const story_game *g, int index) {
    return index < g->detour_count ? &g->detours[index] : &g->more_detours[index - g->detour_count];
}

/* Verify every site of this game, then write every one -- or write nothing. */
static int install(int game) {
    const story_game *g = &GAMES[game];
    unsigned char bytes[16];
    int i;
    for (i = 0; i < g->write_count; ++i) {
        if (!mem_matches(g->writes[i].va, g->writes[i].expect, g->writes[i].length)) {
            return 0;
        }
    }
    for (i = 0; i < game_detour_count(g); ++i) {
        const story_detour *d = game_detour(g, i);
        if (d->length > (int)sizeof bytes || !mem_matches(d->va, d->expect, d->length)) {
            return 0;
        }
    }
    for (i = 0; i < g->write_count; ++i) {
        if (!mem_write(g->writes[i].va, g->writes[i].replace, g->writes[i].length)) {
            return 0;
        }
    }
    for (i = 0; i < game_detour_count(g); ++i) {
        const story_detour *d = game_detour(g, i);
        detour_bytes(d, bytes);
        if (!mem_write(d->va, bytes, d->length)) {
            return 0;
        }
    }
    return 1;
}

/* Called by the Origins companion of `game` (1-5) from its own per-frame or
   menu path, outside DllMain.  Idempotent.  Returns whether the free prices
   and the Pick Island Event detour are in place. */
__declspec(dllexport) int __stdcall VvfpStoryInstall(int game) {
    if (game < 1 || game > 5) {
        return 0;
    }
    if (install_state[game] == 0) {
        install_state[game] = install(game) ? 1 : -1;
    }
    if (install_state[game] == 1) {
        /* The Origins companion calls this from its per-frame path: the
           custom titles' tick (bind to the save slot, notice a Start Over,
           forget the titles of villagers who are gone). */
        static DWORD last_tick;
        DWORD now = GetTickCount();
        if (now - last_tick >= TICK_MS) {
            last_tick = now;
            titles_tick(game);
        }
    }
    return install_state[game] == 1;
}

/* Whether this game's Origins upgrades are free right now: the Origins
   companion shows 0 and charges 0 in its own prompts only when this is 1. */
__declspec(dllexport) int __stdcall VvfpStoryActive(int game) {
    return game >= 1 && game <= 5 && install_state[game] == 1;
}

/* ---- The chooser ----------------------------------------------------------- */

static struct {
    const story_game *game;
    int possible[STORY_MAX_EVENTS];
    int chosen;
} chooser;

static void label_of(const story_event *e, char *out, size_t size) {
    if (e->variant != NULL && e->variant[0] != '\0') {
        wsprintfA(out, "%s (%s)", e->title, e->variant);
    } else {
        lstrcpynA(out, e->title, (int)size);
    }
}

static void chooser_show(HWND window) {
    int sel = (int)SendDlgItemMessageA(window, IDC_PICK_LIST, LB_GETCURSEL, 0, 0);
    int index;
    char text[512];
    if (sel < 0) {
        SetDlgItemTextA(window, IDC_PICK_DESC, "");
        EnableWindow(GetDlgItem(window, IDOK), FALSE);
        return;
    }
    index = (int)SendDlgItemMessageA(window, IDC_PICK_LIST, LB_GETITEMDATA, (WPARAM)sel, 0);
    if (chooser.possible[index]) {
        lstrcpynA(text, chooser.game->events[index].description, sizeof text);
    } else {
        wsprintfA(text, "%s\r\n\r\nNot possible right now: %s",
                  chooser.game->events[index].description,
                  chooser.game->events[index].requires);
    }
    SetDlgItemTextA(window, IDC_PICK_DESC, text);
    EnableWindow(GetDlgItem(window, IDOK), chooser.possible[index]);
}

static INT_PTR CALLBACK chooser_dialog(HWND window, UINT message, WPARAM wparam, LPARAM lparam) {
    (void)lparam;
    if (message == WM_INITDIALOG) {
        int i;
        char label[160];
        for (i = 0; i < chooser.game->event_count; ++i) {
            int row;
            label_of(&chooser.game->events[i], label, sizeof label);
            if (!chooser.possible[i]) {
                lstrcatA(label, " - not possible right now");
            }
            row = (int)SendDlgItemMessageA(window, IDC_PICK_LIST, LB_ADDSTRING, 0, (LPARAM)label);
            SendDlgItemMessageA(window, IDC_PICK_LIST, LB_SETITEMDATA, (WPARAM)row, (LPARAM)i);
        }
        chooser_show(window);
        return TRUE;
    }
    if (message == WM_COMMAND) {
        if (LOWORD(wparam) == IDC_PICK_LIST && HIWORD(wparam) == LBN_SELCHANGE) {
            chooser_show(window);
            return TRUE;
        }
        if (LOWORD(wparam) == IDC_PICK_LIST && HIWORD(wparam) == LBN_DBLCLK) {
            if (IsWindowEnabled(GetDlgItem(window, IDOK))) {
                PostMessageA(window, WM_COMMAND, IDOK, 0);
            }
            return TRUE;
        }
        if (LOWORD(wparam) == IDOK) {
            int sel = (int)SendDlgItemMessageA(window, IDC_PICK_LIST, LB_GETCURSEL, 0, 0);
            int index;
            if (sel < 0) {
                return TRUE;
            }
            index = (int)SendDlgItemMessageA(window, IDC_PICK_LIST, LB_GETITEMDATA, (WPARAM)sel, 0);
            if (!chooser.possible[index]) {
                return TRUE;
            }
            chooser.chosen = index;
            EndDialog(window, IDOK);
            return TRUE;
        }
        if (LOWORD(wparam) == IDCANCEL) {
            EndDialog(window, IDCANCEL);
            return TRUE;
        }
    } else if (message == WM_CLOSE) {
        EndDialog(window, IDCANCEL);
        return TRUE;
    }
    return FALSE;
}

/* Arms `event` for `game`: makes the island event due and remembers the
   pick.  1 on success. */
static int arm_pick(int game, const story_event *event) {
    if (!GAMES[game].arm()) {
        return 0;
    }
    pick_slot = event->slot;
    pick_game = game;
    pick_tick = STORY_TICK();
    pick_event = event;
    pick_village = story_village_now(game);
    return 1;
}

/* Called by "VVFP Save Reset.dll" (ResetDeletedTribe) when the player
   deletes a tribe or starts over: the village a queued event was for is
   gone (or replaced in the same slot), so every queued event is discarded. */
__declspec(dllexport) void __stdcall VvfpStoryVillageReset(int game, int slot) {
    (void)game;
    (void)slot;
    ++story_village_generation;
}

/* The Pick Island Event upgrade, called by the Origins companion when its
   Pick Island Event button is clicked (the companion has already refused a
   click while the Island Event row is locked).  Shows the chooser, confirms
   the 0-point purchase, and arms the pick.  Returns 1 when an event is on
   its way, 0 otherwise. */
__declspec(dllexport) int __stdcall VvfpStoryPickIslandEvent(int game, HWND owner) {
    const story_game *g;
    const story_event *event;
    char label[160];
    char message[512];
    int i;
    if (!VvfpStoryActive(game)) {
        return 0;
    }
    g = &GAMES[game];
    drop_lapsed_pick();
    ce_drop_lapsed();
    if (pick_slot >= 0 || ce_armed || g->island_pending()) {
        /* New Believers' Island Event and Barrel of Babies share one queue
           (either blocks both purchases); the pick shares it too. */
        MessageBoxA(owner,
                    game == 5
                        ? "An island event or a barrel of babies is already queued "
                          "and on its way.\n\nIt arrives shortly. Close this screen "
                          "and wait for it to arrive."
                        : "An island event is already queued and on its way.\n\n"
                          "It arrives shortly. Close this screen and wait for it to arrive.",
                    "Not right now", MB_OK | MB_ICONINFORMATION | MB_TOPMOST | MB_SETFOREGROUND);
        return 0;
    }
    if (last_failed_event != NULL) {
        label_of(last_failed_event, label, sizeof label);
        if (last_failed_lapsed) {
            wsprintfA(message,
                      "The last island event you picked, %s, did not happen within "
                      "ten minutes, so it was cancelled.", label);
        } else {
            wsprintfA(message,
                      "The last island event you picked, %s, could not happen when it "
                      "was due (it needs %s), so the island event the game chose "
                      "happened instead.",
                      label, last_failed_event->requires);
        }
        MessageBoxA(owner, message, "Pick Island Event",
                    MB_OK | MB_ICONINFORMATION | MB_TOPMOST | MB_SETFOREGROUND);
        last_failed_event = NULL;
    }
    chooser.game = g;
    chooser.chosen = -1;
    for (i = 0; i < g->event_count && i < STORY_MAX_EVENTS; ++i) {
        chooser.possible[i] = g->possible(&g->events[i]);
    }
    if (DialogBoxParamA(module_instance, MAKEINTRESOURCEA(IDD_PICK), owner, chooser_dialog, 0)
            != IDOK
        || chooser.chosen < 0) {
        return 0;
    }
    event = &g->events[chooser.chosen];
    label_of(event, label, sizeof label);
    wsprintfA(message,
              "Do you want to buy Pick Island Event (%s) for 0 tech points?\r\n"
              "Press OK to confirm, or Cancel.", label);
    if (MessageBoxA(owner, message, "Origins Upgrades",
                    MB_OKCANCEL | MB_ICONQUESTION | MB_TOPMOST | MB_SETFOREGROUND) != IDOK) {
        return 0;
    }
    /* The village may have moved on while the boxes were open. */
    if (ce_armed || g->island_pending() || !g->possible(event) || !arm_pick(game, event)) {
        MessageBoxA(owner, "That island event can not happen right now. No tech points have been deducted.",
                    "Origins Upgrades", MB_OK | MB_ICONINFORMATION | MB_TOPMOST | MB_SETFOREGROUND);
        return 0;
    }
    wsprintfA(message, "%s is on its way.", label);
    MessageBoxA(owner, message, "Origins Upgrades",
                MB_OK | MB_ICONINFORMATION | MB_TOPMOST | MB_SETFOREGROUND);
    return 1;
}

/* Whether a pick or a custom event is armed and not yet delivered. */
__declspec(dllexport) int __stdcall VvfpStoryPickPending(int game) {
    drop_lapsed_pick();
    return (pick_slot >= 0 && pick_game == game) || ce_pending(game);
}

#include "story_custom_ui.inc"

BOOL WINAPI DllMain(HINSTANCE instance, DWORD reason, LPVOID reserved) {
    (void)reserved;
    if (reason == DLL_PROCESS_ATTACH) {
        module_instance = instance;
        DisableThreadLibraryCalls(instance);
    }
    return TRUE;
}

#ifdef VVFP_TEST
/* ---- Test build only ------------------------------------------------------- */

/* Site `index` of `game`: its address, the bytes verified there and the bytes
   written.  Returns the length, or 0 past the end.  Detours follow the
   writes; their written bytes are computed for this load of the DLL. */
__declspec(dllexport) int __stdcall VvfpStoryProbeSite(int game, int index, unsigned int *va,
                                                        unsigned char *expect,
                                                        unsigned char *replace) {
    const story_game *g;
    if (game < 1 || game > 5) {
        return 0;
    }
    g = &GAMES[game];
    if (index < g->write_count) {
        *va = g->writes[index].va;
        memcpy(expect, g->writes[index].expect, (size_t)g->writes[index].length);
        memcpy(replace, g->writes[index].replace, (size_t)g->writes[index].length);
        return g->writes[index].length;
    }
    index -= g->write_count;
    if (index < game_detour_count(g)) {
        const story_detour *d = game_detour(g, index);
        *va = d->va;
        memcpy(expect, d->expect, (size_t)d->length);
        detour_bytes(d, replace);
        return d->length;
    }
    return 0;
}

/* Arms a pick by its position in this game's event table without any
   dialog, at test tick `tick`.  Returns the game's index of the event. */
__declspec(dllexport) int __stdcall VvfpStoryProbeArm(int game, int position, DWORD tick) {
    const story_game *g;
    if (game < 1 || game > 5) {
        return -1;
    }
    g = &GAMES[game];
    if (position < 0 || position >= g->event_count) {
        return -1;
    }
    test_tick = tick;
    install_state[game] = 1;
    if (!arm_pick(game, &g->events[position])) {
        return -1;
    }
    return g->events[position].slot;
}

/* Arms a pick WITHOUT making the island event due (the delivery tests drive
   the selector directly). */
__declspec(dllexport) int __stdcall VvfpStoryProbeSetPick(int game, int position, DWORD tick) {
    const story_game *g;
    if (game < 1 || game > 5) {
        return -1;
    }
    g = &GAMES[game];
    if (position < 0 || position >= g->event_count) {
        return -1;
    }
    pick_slot = g->events[position].slot;
    pick_game = game;
    pick_tick = tick;
    pick_event = &g->events[position];
    pick_village = story_village_now(game);
    return pick_slot;
}

__declspec(dllexport) void __stdcall VvfpStoryProbeSetTick(DWORD tick) {
    test_tick = tick;
}

__declspec(dllexport) int __stdcall VvfpStoryProbePending(int game) {
    return GAMES[game].island_pending();
}

__declspec(dllexport) int __stdcall VvfpStoryProbePossible(int game, int position) {
    return GAMES[game].possible(&GAMES[game].events[position]);
}

__declspec(dllexport) int __stdcall VvfpStoryProbeArmedSlot(void) {
    return pick_slot;
}

/* Arms `event` for `game` exactly as the dialog's purchase does, without
   any dialog or check, at test tick `tick`.  1 on success. */
__declspec(dllexport) int __stdcall VvfpStoryProbeQueueCustom(int game, const ce_event *event,
                                                              DWORD tick) {
    if (game < 1 || game > 5) {
        return 0;
    }
    test_tick = tick;
    install_state[game] = 1;
    return ce_arm(game, event);
}

/* Arms `event` WITHOUT making the island event due (the delivery tests
   drive the game's own code directly). */
__declspec(dllexport) int __stdcall VvfpStoryProbeSetCustom(int game, const ce_event *event,
                                                            DWORD tick) {
    ce_armed_event = *event;
    ce_armed_event.game = game;
    ce_armed = 1;
    ce_armed_tick = tick;
    ce_armed_village = story_village_now(game);
    return 1;
}

__declspec(dllexport) int __stdcall VvfpStoryProbeCustomPending(int game) {
    return ce_pending(game);
}

__declspec(dllexport) void __stdcall VvfpStoryProbeResult(ce_result *out) {
    *out = ce_last_result;
}

/* The engine on its own: apply `event` now and compose the popup text. */
__declspec(dllexport) int __stdcall VvfpStoryProbeApply(int game, const ce_event *event,
                                                        ce_result *result, char *text, int size) {
    const ce_adapter *a = ce_adapter_for(game);
    if (a == NULL) {
        return 0;
    }
    ce_apply(a, event, result);
    return ce_compose(a, event, result, text, size);
}

/* Why `event` can not be queued in `game` now (a string), or NULL. */
__declspec(dllexport) const char *__stdcall VvfpStoryProbeRefusal(int game, const ce_event *event) {
    return ce_refusal(game, event);
}

/* The dialog's target list: the roster with `picked` (per roster position)
   and `toggles` combined; writes record indices, returns the count. */
__declspec(dllexport) int __stdcall VvfpStoryProbeTargets(int game, const unsigned char *picked,
                                                          unsigned int toggles, int *out, int cap) {
    static story_member roster[UI_ROSTER_MAX];
    const ce_adapter *a = ce_adapter_for(game);
    int n;
    if (a == NULL) {
        return -1;
    }
    n = ce_roster(a, roster, UI_ROSTER_MAX);
    return story_resolve_targets(roster, n, picked, toggles, a->adult_age, out, cap);
}

/* The dialog's merge of one villager's changes into an event. */
__declspec(dllexport) int __stdcall VvfpStoryProbeMerge(ce_event *event, const ce_change *change,
                                                        int index, unsigned int fingerprint) {
    return ce_merge(event, change, index, fingerprint);
}

__declspec(dllexport) void __stdcall VvfpStoryProbeInitChange(ce_change *change) {
    ce_change_init(change);
}

/* Custom titles without the file: bind the table to `slot` as loaded, with
   no entries; then VvfpStoryProbeTitleSet adds one without publishing. */
__declspec(dllexport) void __stdcall VvfpStoryProbeTitlesLoaded(int game, int slot, const char *path) {
    titles_forget();
    titles.game = game;
    titles.slot = slot;
    titles.loaded = 1;
    titles.file_present = 0;
    lstrcpynA(titles.path, path, MAX_PATH);
    vv_sidecar_gate_bind(&titles.gate, game * 16 + slot);
    lstrcpynA(titles.gate.path, path, MAX_PATH);
    titles.gate.state = VV_SIDECAR_SETTLED;     /* as a load that found no file */
}

__declspec(dllexport) int __stdcall VvfpStoryProbeTitleSet(int game, int index, const char *text) {
    const unsigned char *record = story_record(game, index);
    if (record == NULL || titles.count >= VV_TITLES_MAX) {
        return 0;
    }
    titles.entries[titles.count].index = (unsigned int)index;
    titles.entries[titles.count].fingerprint = story_name_fingerprint(game, record);
    lstrcpynA(titles.entries[titles.count].title, text, VV_TITLE_BYTES);
    titles.seen[titles.count] = 0;
    ++titles.count;
    return 1;
}

__declspec(dllexport) const char *__stdcall VvfpStoryProbeTitleOf(int game, const unsigned char *record) {
    return titles_lookup(game, record);
}

__declspec(dllexport) int __stdcall VvfpStoryProbeTitleCount(void) {
    return titles.count;
}

/* The layout the tests pack events in: sizes of ce_event, ce_spawn,
   ce_change, ce_result, then the offsets of ce_event.spawns, .change_count
   and .changes. */
__declspec(dllexport) void __stdcall VvfpStoryProbeSizes(int *out) {
    out[0] = (int)sizeof(ce_event);
    out[1] = (int)sizeof(ce_spawn);
    out[2] = (int)sizeof(ce_change);
    out[3] = (int)sizeof(ce_result);
    out[4] = (int)offsetof(ce_event, spawns);
    out[5] = (int)offsetof(ce_event, change_count);
    out[6] = (int)offsetof(ce_event, changes);
}

__declspec(dllexport) const void *__stdcall VvfpStoryProbeObject(void) {
    return &ce_object;
}
#endif
