/* VVFP Story Upgrades -- the companion of the "Story / Cheat Upgrades" rows
   (all five games, default-off, requires the Origins upgrades).

   The owner: "Adds optional tools intended for custom stories, experiments,
   sandbox play, and cheats.  ...  When enabled, all Origins Upgrades cost 0
   Tech Points.  Also adds ... Pick Island Event -- Allows the player to
   directly choose which stock Island Event occurs instead of relying on
   random selection.  ...  Custom Island Event -- Allows the player to
   create and trigger a custom Island Event for storytelling, testing,
   sandbox play, or cheats."

   WHAT THIS COMPANION DOES.

   1. Free Origins upgrades.  Every place the Origins payload of the
      executable compares the tech-point balance with a price, deducts a
      price, refunds a price or shows a price is listed in story_tables.h
      (generated by scripts/build_story_cheat_upgrades_features.py, which
      checks every listed byte against the executable the patcher renders, in
      all three population modes).  VvfpStoryInstall verifies EVERY listed
      site first and writes nothing unless all of them hold exactly the bytes
      the Origins payload put there; then it writes the zero-cost bytes.  So
      the feature is all or nothing: a build whose Origins bytes differ gets
      no change at all, and the Origins companion keeps showing and charging
      the normal prices (it asks VvfpStoryActive before showing 0).
      A price of 0 keeps every lock: `cmp balance, 0; jb` never refuses, and
      every pending, capacity and "nothing to change" refusal still runs.

   2. Pick Island Event.  The player picks one of the game's own island
      events from a plain dialog.  The pick then makes the island event due
      exactly as the Origins "Island Event" purchase does (the same fields,
      so the same pending lock), and when the game's own scheduler fires that
      event, a detour at the point where the game has just chosen WHICH event
      to run replaces the random choice with the picked one -- and only if
      the game's own condition for that event holds at that moment.  The
      event is then created, shown and resolved by the game's own code, with
      its own random outcomes, choices and amounts; nothing about the event
      itself is emulated here.

   3. Custom Island Event (story_custom*.inc, story_c1..5.inc).  The player
      builds an event -- its title and description, village changes, new
      villagers, per-villager changes -- in plain dialogs; it is armed like a
      pick (the same lock: one pick or custom event at a time) and, when the
      game's own scheduler fires the island event, the game's own island
      event popup shows the custom title and description and the changes are
      made through each game's own routines.  Only what each game's own code
      was traced to support is offered in that game.

   4. Custom titles (story_titles.inc, native/shared/custom_titles.h): a
      villager's title replaced by the player's text in the villager panel,
      kept per save slot in a .dat file beside the saves.

   Installed at run time by VvfpStoryInstall(game) from the Origins
   companion (once it runs in the game process, outside DllMain).  The stock
   or Origins bytes at every site are verified first. */
#include <windows.h>
#include <string.h>
#include <intrin.h>
#include <stddef.h>

/* Each game's adapter table is declared before the functions that name it
   and defined after them (a tentative definition, standard C). */
#pragma warning(disable : 4132)

#include "story_tables.h"
#include "../shared/custom_titles.h"
#include "../shared/sidecar_io.h"
#include "../shared/save_folder.h"
#include "../shared/patcher_files.h"
#include "story_targets.h"
#include "story_custom.h"

enum {
    IDD_PICK = 301,
    IDC_PICK_LIST = 3001,
    IDC_PICK_DESC = 3002
};

#define PICK_TIMEOUT_MS (10u * 60u * 1000u)   /* an undelivered pick lapses after 10 minutes */
#define CAN_FIRE_TRIES 16                      /* see can_fire_with_retries */
#define TICK_MS 250u                           /* the custom titles' sweep, at most this often */

static HINSTANCE module_instance;
static int install_state[6];      /* 0 = not tried, 1 = active, -1 = refused */

/* The village a pick or a custom event was queued in: its save slot (as the
   Origins companion keys its own sidecars) and the reset generation, which
   VvfpStoryVillageReset advances whenever a tribe is deleted or started
   over.  A queued event is delivered only into that same village; loading
   another slot, Start Over or deleting a tribe discards it, so it can never
   replace another village's event or change its villagers. */
typedef struct {
    int slot;
    unsigned int generation;
} story_village;
static unsigned int story_village_generation;
static int story_current_slot(int game);

static story_village story_village_now(int game) {
    story_village v;
    v.slot = story_current_slot(game);
    v.generation = story_village_generation;
    return v;
}

static int story_village_is(int game, const story_village *v) {
    return v->slot == story_current_slot(game) && v->generation == story_village_generation;
}

/* The armed pick: the game's own index of the chosen event (-1 = none),
   when it was armed, and the table entry it came from. */
static int pick_slot = -1;
static int pick_game;
static DWORD pick_tick;
static const story_event *pick_event;
static story_village pick_village;
/* The outcome of the last pick, shown the next time the chooser opens when
   the game could not run it. */
static const story_event *last_failed_event;

#ifdef VVFP_TEST
/* Counters the tests read.  Compiled only into the TEST build. */
struct vvfp_story_stats {
    int delivered;      /* a picked or custom event replaced the game's own */
    int refused;        /* the picked event's own condition did not hold */
    int lapsed;         /* an armed pick or custom event was dropped as too old */
    int discarded;      /* an armed pick or custom event was dropped: another village */
};
__declspec(dllexport) struct vvfp_story_stats VvfpStoryStats = { 0 };
#define STORY_COUNT(field) (++VvfpStoryStats.field)
static DWORD test_tick;
#define STORY_TICK() (test_tick)
#else
#define STORY_COUNT(field) ((void)0)
#define STORY_TICK() (GetTickCount())
#endif

/* Defined with the Custom Island Event (story_custom.inc), used earlier. */
static int ce_pending(int game);
/* Defined with the outcomes (story_outcomes.inc), used earlier. */
static void oc_new_choice(int game);
static void oc_delivered(int game, void *object);
static void oc_lapsed(void);
static void oc_refused(int game);
static void oc_reroll(int game);
static int oc_unlocked(int game, int slot);
static int oc_unlock_ready(int game, int slot, const void *object);
static void oc_unlock_prepare(int game, int slot, void *object);
static void oc_island_begin(int game);
static void oc_island_end(int game);
static int vv1_island_strength(void);
static void *c3_custom_object(void);
static void *c4_custom_object(void);
static void *c5_custom_object(void);
static int ce_choice_pending(int game);
static void *c3_choice_object(void);
static void *c4_choice_object(void);
static void *c5_choice_object(void);
static unsigned int choice_resolve_target(int game, unsigned int va, unsigned int ecx);
/* ---- Memory ---------------------------------------------------------------- */

static int mem_readable(unsigned int va, int length) {
    MEMORY_BASIC_INFORMATION info;
    const void *at = (const void *)(uintptr_t)va;
    if (VirtualQuery(at, &info, sizeof(info)) != sizeof(info) || info.State != MEM_COMMIT
        || (info.Protect & (PAGE_NOACCESS | PAGE_GUARD)) != 0) {
        return 0;
    }
    return (uintptr_t)at + (unsigned int)length
           <= (uintptr_t)info.BaseAddress + info.RegionSize;
}

static int mem_matches(unsigned int va, const unsigned char *bytes, int length) {
    if (!mem_readable(va, length)) {
        return 0;
    }
    return memcmp((const void *)(uintptr_t)va, bytes, (size_t)length) == 0;
}

#ifdef VVFP_TEST
/* TEST build only: the write that fails (0 = the first), -1 = none. */
static int test_fail_write = -1;
#endif

static int mem_write(unsigned int va, const unsigned char *bytes, int length) {
    DWORD old;
    void *at = (void *)(uintptr_t)va;
#ifdef VVFP_TEST
    if (test_fail_write >= 0 && test_fail_write-- == 0) {
        return 0;
    }
#endif
    if (!VirtualProtect(at, (SIZE_T)length, PAGE_EXECUTE_READWRITE, &old)) {
        return 0;
    }
    memcpy(at, bytes, (size_t)length);
    VirtualProtect(at, (SIZE_T)length, old, &old);
    FlushInstructionCache(GetCurrentProcess(), at, (SIZE_T)length);
    return 1;
}

static unsigned int read_u32(unsigned int va) {
    return *(volatile unsigned int *)(uintptr_t)va;
}

/* The bytes a detour writes at its site: a jmp (or, for a call site, a call)
   to the stub, padded with nops. */
static void detour_bytes(const story_detour *d, unsigned char *out) {
    unsigned int rel = (unsigned int)((uintptr_t)d->stub - ((uintptr_t)d->va + 5));
    int i;
    out[0] = d->is_call ? 0xE8 : 0xE9;
    memcpy(out + 1, &rel, 4);
    for (i = 5; i < d->length; ++i) {
        out[i] = 0x90;
    }
}

/* ---- Per-game event code -------------------------------------------------- */

typedef char (__fastcall *can_fire_fn)(void *self, void *unused_edx);
typedef void *(__cdecl *getter_fn)(void);

/* The game's own condition for an event object (vtable slot 1, thiscall, no
   arguments).  Several conditions roll the game's random generator or pick
   the villager the event will be about (stored in the object), so a false
   answer can be random rather than final: it is asked a few times before the
   event is called impossible.  A true answer leaves the object exactly as
   the game's own selector would have left it before running the event. */
static int can_fire_with_retries(void *object) {
    int i;
    for (i = 0; i < CAN_FIRE_TRIES; ++i) {
        can_fire_fn can_fire = (can_fire_fn)(*(void ***)object)[1];
        if (can_fire(object, NULL)) {
            return 1;
        }
    }
    return 0;
}

/* An armed pick that the game has not run within PICK_TIMEOUT_MS is
   dropped (so a pick can never carry over into a village loaded much later);
   the next chooser says so.  Returns 1 when a pick was dropped. */
static int last_failed_lapsed;

static int drop_lapsed_pick(void) {
    if (pick_slot >= 0 && !story_village_is(pick_game, &pick_village)) {
        /* Another village: the pick was for the one the player left. */
        pick_slot = -1;
        STORY_COUNT(discarded);
        return 1;
    }
    if (pick_slot >= 0 && STORY_TICK() - pick_tick > PICK_TIMEOUT_MS) {
        pick_slot = -1;
        oc_lapsed();
        last_failed_event = pick_event;
        last_failed_lapsed = 1;
        STORY_COUNT(lapsed);
        return 1;
    }
    return 0;
}

/* Takes the armed pick for `game` (and clears it): the game's index of the
   event, or -1. */
static int take_pick(int game) {
    int slot;
    if (drop_lapsed_pick()) {
        return -1;
    }
    slot = pick_slot;
    if (slot < 0 || pick_game != game) {
        return -1;
    }
    pick_slot = -1;
    return slot;
}

/* For VV3, VV4 and VV5: the selector has just chosen `current`; return the
   index the selector should use.  `table` is the game's event-object array. */
static int choose_from_table(int game, unsigned int table, int current) {
    void *object;
    const story_event *event = pick_event;
    int slot = take_pick(game);
    if (slot < 0) {
        return current;
    }
    object = *(void **)(uintptr_t)(table + 4u * (unsigned int)slot);
    if (object != NULL && oc_unlocked(game, slot)) {
        oc_unlock_prepare(game, slot, object);
    }
    if (object != NULL && (can_fire_with_retries(object)
                           || (oc_unlocked(game, slot) && oc_unlock_ready(game, slot, object)))) {
        STORY_COUNT(delivered);
        last_failed_event = NULL;
        oc_delivered(game, object);
        return slot;
    }
    STORY_COUNT(refused);
    oc_refused(game);
    last_failed_event = event;
    last_failed_lapsed = 0;
    return current;
}

/* The Secret City.  0x419BDB `mov edx, [esi*4 + 0x4B3C78]` is where the
   selector 0x419B30 has settled on `esi` (after its own random pick and its
   rescue override) and is about to build the event dialog.  A custom event
   armed for this game is presented here instead (story_c3.inc); otherwise
   an armed pick replaces the choice.

   The Origins Barrel of Babies delivers its barrel by calling the same
   selector with EVERY slot pointing at the barrel object (0x47B3E0); neither
   a pick nor a custom event is consumed there, because what would run is
   the barrel.  All slots equal is that state and never the game's own.

   Returns the object to present instead of the table's, or NULL (and the
   slot the selector should use in *slot). */
static void *__cdecl vv3_select(int *slot) {
    void *custom;
    oc_new_choice(3);
    if (read_u32(VV3_EVENT_TABLE + 4) == read_u32(VV3_EVENT_TABLE + 8)) {
        return NULL;
    }
    custom = c3_choice_object();      /* a question (story_objects.inc) */
    if (custom == NULL) {
        custom = c3_custom_object();
    }
    if (custom != NULL) {
        return custom;
    }
    *slot = choose_from_table(3, VV3_EVENT_TABLE, *slot);
    return NULL;
}

/* pushad stores EDI, ESI, EBP, ESP, EBX, EDX, ECX, EAX from [esp] up, so the
   saved ESI is [esp+4] and the saved EAX [esp+0x1C]. */
__declspec(naked) static void vv3_stub(void) {
    __asm {
        pushad
        lea eax, [esp + 4]
        push eax
        call vv3_select
        add esp, 4
        mov dword ptr [esp + 0x1C], eax
        popad
        test eax, eax
        jnz custom
        mov edx, dword ptr [esi * 4 + 0x4B3C78]
        push 0x419BE2
        ret
    custom:
        mov edx, eax
        push 0x419BE2
        ret
    }
}

/* The Tree of Life.  0x4180F7 `mov eax, [esi*4 + 0x4CCA28]`: the selector
   0x418000 has settled on `esi` (after the random pick and the rescue
   override) and is about to present it.  The Origins Barrel delivers through
   0x418190 instead, which never passes here. */
static void *__cdecl vv4_select(int *slot) {
    void *custom;
    oc_new_choice(4);
    custom = c4_choice_object();      /* a question (story_objects.inc) */
    if (custom == NULL) {
        custom = c4_custom_object();
    }
    if (custom != NULL) {
        return custom;
    }
    *slot = choose_from_table(4, VV4_EVENT_TABLE, *slot);
    return NULL;
}

__declspec(naked) static void vv4_stub(void) {
    __asm {
        pushad
        lea eax, [esp + 4]
        push eax
        call vv4_select
        add esp, 4
        mov dword ptr [esp + 0x1C], eax
        popad
        test eax, eax
        jnz custom
        mov eax, dword ptr [esi * 4 + 0x4CCA28]
    custom:
        push 0x4180FE
        ret
    }
}

/* New Believers.  0x41895B `mov eax, [esi*4 + 0x4DC850]`: after the Origins
   selector stub (0x41890F, the purchased Barrel) and the stock Chutes Without
   Ladders override, so nothing later can replace the pick.  A purchased
   Barrel shares the Island Event lock, so it is never armed together with a
   custom event. */
static void *__cdecl vv5_select(int *slot) {
    void *custom;
    oc_new_choice(5);
    custom = c5_choice_object();      /* a question (story_objects.inc) */
    if (custom == NULL) {
        custom = c5_custom_object();
    }
    if (custom != NULL) {
        return custom;
    }
    *slot = choose_from_table(5, VV5_EVENT_TABLE, *slot);
    return NULL;
}

__declspec(naked) static void vv5_stub(void) {
    __asm {
        pushad
        lea eax, [esp + 4]
        push eax
        call vv5_select
        add esp, 4
        mov dword ptr [esp + 0x1C], eax
        popad
        test eax, eax
        jnz custom
        mov eax, dword ptr [esi * 4 + 0x4DC850]
    custom:
        push 0x418962
        ret
    }
}

/* Each game's clock (seconds), thiscall on the world object. */
typedef int (__fastcall *clock_fn)(void *self, void *unused_edx);

#include "story_vv1.inc"
#include "story_vv2.inc"

/* ---- Making the island event due ------------------------------------------ */

/* Each game: is an island event already on its way (the Island Event row's
   own lock), and make one due exactly as the Origins Island Event purchase
   does.  Returns 1 on success. */
static int vv3_island_pending(void) {
    return *(volatile unsigned char *)(uintptr_t)VV3_ISLAND_FLAG != 0;
}

static int vv3_arm(void) {
    void *manager = *(void **)(uintptr_t)VV3_MANAGER_GLOBAL;
    void (__fastcall *queue_arm_island)(void *, void *) =
        (void (__fastcall *)(void *, void *))(uintptr_t)VV3_QUEUE_ARM_ISLAND;
    if (manager == NULL) {
        return 0;
    }
    queue_arm_island(manager, NULL);   /* the Island Event purchase's own helper */
    return 1;
}

static int vv4_island_pending(void) {
    unsigned char *world = *(unsigned char **)(uintptr_t)VV4_WORLD_GLOBAL;
    unsigned int countdown;
    if (world == NULL) {
        return 1;
    }
    countdown = *(unsigned int *)(world + VV4_COUNTDOWN);
    if (*(volatile unsigned char *)(uintptr_t)VV4_ISLAND_TOKEN != 0
        && (countdown == read_u32(VV4_ISLAND_STAMP)
            || *(volatile unsigned char *)(uintptr_t)VV4_BARREL_ARMED != 0)) {
        return 1;
    }
    if (countdown == 0) {
        return 1;
    }
    return countdown - (unsigned int)((clock_fn)(uintptr_t)VV4_CLOCK)(world, NULL) <= 5u;
}

static int vv4_arm(void) {
    unsigned char *world = *(unsigned char **)(uintptr_t)VV4_WORLD_GLOBAL;
    unsigned int due;
    if (world == NULL) {
        return 0;
    }
    due = (unsigned int)((clock_fn)(uintptr_t)VV4_CLOCK)(world, NULL) + 5u;
    *(unsigned int *)(world + VV4_COUNTDOWN) = due;
    *(volatile unsigned char *)(uintptr_t)VV4_ISLAND_TOKEN = 1;
    *(volatile unsigned int *)(uintptr_t)VV4_ISLAND_STAMP = due;
    return 1;
}

static int vv5_island_pending(void) {
    return (read_u32(VV5_PURCHASE_FLAGS) & 0x3Cu) != 0;
}

static int vv5_arm(void) {
    unsigned char *world = *(unsigned char **)(uintptr_t)VV5_WORLD_GLOBAL;
    if (world == NULL) {
        return 0;
    }
    *(unsigned int *)(world + VV5_COUNTDOWN) = 0;
    *(volatile unsigned int *)(uintptr_t)VV5_PURCHASE_FLAGS |= 0x10u;
    return 1;
}

/* Whether the game's own condition for an event holds right now.  VV3-VV5:
   the event object's own condition, through the game's own event table
   (built by the game's own getter if no event has run yet this session). */
static int table_event_possible(unsigned int table, getter_fn getter, int slot) {
    void *object = *(void **)(uintptr_t)(table + 4u * (unsigned int)slot);
    if (object == NULL) {
        getter();
        object = *(void **)(uintptr_t)(table + 4u * (unsigned int)slot);
    }
    return object != NULL && can_fire_with_retries(object);
}

static int vv3_possible(const story_event *e) {
    return table_event_possible(VV3_EVENT_TABLE, (getter_fn)(uintptr_t)VV3_EVENT_GETTER, e->slot);
}

static int vv4_possible(const story_event *e) {
    return table_event_possible(VV4_EVENT_TABLE, (getter_fn)(uintptr_t)VV4_EVENT_GETTER, e->slot);
}

static int vv5_possible(const story_event *e) {
    return table_event_possible(VV5_EVENT_TABLE, (getter_fn)(uintptr_t)VV5_EVENT_GETTER, e->slot);
}

/* ---- Custom Island Event -------------------------------------------------- */

/* The record helpers the custom titles use (story_titles.inc), defined with
   the adapters below. */
static int story_record_count(int game);
static unsigned char *story_record(int game, int index);
static int story_record_index(int game, const unsigned char *record);
static int story_record_present(int game, const unsigned char *record);
static unsigned int story_title_identity(int game, const unsigned char *record);
static unsigned int story_title_stable(int game, const unsigned char *record);
static const char *titles_lookup(int game, const unsigned char *record);
static int titles_set(int game, int index, const char *text);
static int titles_rebind(int game, int index, unsigned int before);

#include "story_common.inc"
#include "story_custom.inc"
#include "story_objects.inc"
#include "story_c1.inc"
#include "story_c2.inc"
#include "story_c3.inc"
#include "story_c4.inc"
#include "story_c5.inc"
#include "story_fast_delivery.inc"

static const ce_adapter *ce_adapter_for(int game) {
    switch (game) {
    case 1: return &C1_ADAPTER;
    case 2: return &C2_ADAPTER;
    case 3: return c3_adapter();
    case 4: return c4_adapter();
    case 5: return c5_adapter();
    default: return NULL;
    }
}

static int story_record_count(int game) {
    const ce_adapter *a = ce_adapter_for(game);
    return a != NULL ? a->record_count : 0;
}

static unsigned char *story_record(int game, int index) {
    const ce_adapter *a = ce_adapter_for(game);
    return a != NULL ? a->record(index) : NULL;
}

static int story_record_index(int game, const unsigned char *record) {
    const ce_adapter *a = ce_adapter_for(game);
    int i;
    if (a == NULL || record == NULL) {
        return -1;
    }
    for (i = 0; i < a->record_count; ++i) {
        if (a->record(i) == record) {
            return i;
        }
    }
    return -1;
}

/* A villager is still here: living, or a skeleton not yet buried or
   crumbled away (a revive can bring them back, so their custom title stays
   until the record is freed or holds someone else). */
static int story_record_present(int game, const unsigned char *record) {
    const ce_adapter *a = ce_adapter_for(game);
    return a != NULL && record != NULL
        && (a->listed(record) || (a->skeleton != NULL && a->skeleton(record)));
}

static unsigned int story_title_identity(int game, const unsigned char *record) {
    const ce_adapter *a = ce_adapter_for(game);
    return a != NULL ? vv_title_identity(record, a->off_name, (unsigned int)a->name_bytes, a->off_likes,
                                         a->off_dislikes, (unsigned int)a->pref_slots) : 0;
}

/* What a rename leaves of the title identity: the sex, likes and dislikes
   (story_titles.inc tells a rename from a new occupant by it).  Never 0. */
static unsigned int story_title_stable(int game, const unsigned char *record) {
    const ce_adapter *a = ce_adapter_for(game);
    unsigned int h;
    if (a == NULL) {
        return 0;
    }
    h = vv_title_identity(record, a->off_name, 0u, a->off_likes, a->off_dislikes, (unsigned int)a->pref_slots);
    h = (h ^ (unsigned int)*(const int *)(record + a->off_sex)) * 16777619u;
    return h ? h : 1u;
}

#include "story_titles.inc"
#include "story_outcomes.inc"

/* ---- The per-game table ---------------------------------------------------- */

typedef struct {
    const story_write *writes;
    int write_count;
    const story_detour *detours;
    int detour_count;
    const story_detour *more_detours;   /* VV1 / VV2: the custom event's own sites */
    int more_detour_count;
    const story_event *events;
    int event_count;
    int (*possible)(const story_event *event);
    int (*island_pending)(void);
    int (*arm)(void);
} story_game;

/* The Custom Island Event's own sites follow each game's pick sites: its
   delivery (VV1 / VV2: the island event's chooser call; VV3-VV5: the pick
   site itself), the villager panel's title (story_c*.inc), and VV1 / VV2's
   two-choice setup call, where a question is asked. */
static story_detour vv1_custom_detours[] = {
    { 0x428777u, 5, VV1_CUSTOM_CHOOSE_BYTES, 1, (void *)c1_choose },
    { 0x41FD75u, 5, VV1_TITLE_SITE_BYTES, 0, (void *)c1_title_stub },
    { 0x41A51Fu, 5, VV1_CHOICE_SETUP_BYTES, 1, (void *)c1_choice_setup },
    { 0x4237DDu, 5, VV1_EVENT_PICK_BYTES, 1, (void *)c1_event_pick },
};
static story_detour vv2_custom_detours[] = {
    { 0x4349B2u, 5, VV2_CUSTOM_CHOOSE_BYTES, 1, (void *)c2_choose },
    { 0x429DE3u, 5, VV2_TITLE_SITE_BYTES, 1, (void *)c2_title },
    { 0x42244Au, 5, VV2_CHOICE_SETUP_BYTES, 1, (void *)c2_choice_setup },
    { 0x42EEEDu, 5, VV2_EVENT_PICK_BYTES, 1, (void *)c2_event_pick },
};
static story_detour vv3_detours[] = {
    { VV3_PICK_SITE, 7, VV3_PICK_SITE_BYTES, 0, (void *)vv3_stub },
    { 0x468FC8u, 6, VV3_TITLE_SITE_BYTES, 0, (void *)c3_title_stub },
    { 0x419A29u, 12, VV3_OC_CHOICE_APPLY_BYTES, 0, (void *)oc_vv3_choice_stub },
    { 0x419A41u, 5, VV3_OC_SIMPLE_APPLY_BYTES, 0, (void *)oc_vv3_simple_stub },
    { 0x468757u, 5, VV3_EVENT_PICK_BYTES, 1, (void *)c3_event_pick },
};
static story_detour vv4_detours[] = {
    { VV4_PICK_SITE, 7, VV4_PICK_SITE_BYTES, 0, (void *)vv4_stub },
    { 0x4404D9u, 5, VV4_TITLE_SITE_BYTES, 0, (void *)c4_title_stub },
    { 0x417EC9u, 16, VV4_OC_CHOICE_APPLY_BYTES, 0, (void *)oc_vv4_choice_stub },
    { 0x417EE5u, 9, VV4_OC_SIMPLE_APPLY_BYTES, 0, (void *)oc_vv4_simple_stub },
    { 0x43FA70u, 5, VV4_EVENT_PICK_BYTES, 1, (void *)c4_event_pick },
};
static story_detour vv5_detours[] = {
    { VV5_PICK_SITE, 7, VV5_PICK_SITE_BYTES, 0, (void *)vv5_stub },
    { 0x44319Eu, 6, VV5_TITLE_SITE_BYTES, 0, (void *)c5_title_stub },
    { 0x418749u, 16, VV5_OC_CHOICE_APPLY_BYTES, 0, (void *)oc_vv5_choice_stub },
    { 0x418765u, 9, VV5_OC_SIMPLE_APPLY_BYTES, 0, (void *)oc_vv5_simple_stub },
    { 0x44272Fu, 5, VV5_EVENT_PICK_BYTES, 1, (void *)c5_event_pick },
};

static const story_game GAMES[6] = {
    { 0 },
    { VV1_WRITES, VV1_WRITE_COUNT, vv1_detours, sizeof vv1_detours / sizeof vv1_detours[0],
      vv1_custom_detours, sizeof vv1_custom_detours / sizeof vv1_custom_detours[0],
      VV1_EVENTS, VV1_EVENT_COUNT, vv1_possible, vv1_island_pending, vv1_arm },
    { VV2_WRITES, VV2_WRITE_COUNT, vv2_detours, sizeof vv2_detours / sizeof vv2_detours[0],
      vv2_custom_detours, sizeof vv2_custom_detours / sizeof vv2_custom_detours[0],
      VV2_EVENTS, VV2_EVENT_COUNT, vv2_possible, vv2_island_pending, vv2_arm },
    { VV3_WRITES, VV3_WRITE_COUNT, vv3_detours, sizeof vv3_detours / sizeof vv3_detours[0], NULL, 0,
      VV3_EVENTS, VV3_EVENT_COUNT, vv3_possible, vv3_island_pending, vv3_arm },
    { VV4_WRITES, VV4_WRITE_COUNT, vv4_detours, sizeof vv4_detours / sizeof vv4_detours[0], NULL, 0,
      VV4_EVENTS, VV4_EVENT_COUNT, vv4_possible, vv4_island_pending, vv4_arm },
    { VV5_WRITES, VV5_WRITE_COUNT, vv5_detours, sizeof vv5_detours / sizeof vv5_detours[0], NULL, 0,
      VV5_EVENTS, VV5_EVENT_COUNT, vv5_possible, vv5_island_pending, vv5_arm },
};

/* ---- Installing ------------------------------------------------------------ */

/* "Story / Cheat Upgrades cost Tech Points" (the owner, 2026-10-06): set by
   the Origins companion from the patcher's startup flag before the install,
   so the zero prices are never written -- the Origins menus show and charge
   their own prices -- and Pick Island Event, Custom Island Event and Pick
   Gong of Wonder Outcome each cost what the Island Event upgrade costs. */
#define STORY_EVENT_PRICE 30000         /* the Island Event upgrade, all five games */
static int charges[6];

/* The detour `index` of this game: its pick sites, then the custom
   event's own. */
static int game_detour_count(const story_game *g) {
    return g->detour_count + g->more_detour_count;
}

static const story_detour *game_detour(const story_game *g, int index) {
    return index < g->detour_count ? &g->detours[index] : &g->more_detours[index - g->detour_count];
}

/* A write failed part-way: put the stock bytes back at the first `writes`
   price sites and the first `detours` detour sites, which were written, so
   a game reported inactive has none of the feature live. */
static void install_undo(const story_game *g, int writes, int detours) {
    int i;
    for (i = 0; i < detours; ++i) {
        const story_detour *d = game_detour(g, i);
        mem_write(d->va, d->expect, d->length);
    }
    for (i = 0; i < writes; ++i) {
        mem_write(g->writes[i].va, g->writes[i].expect, g->writes[i].length);
    }
}

/* Verify every site of this game, then write every one -- or write nothing. */
static int install(int game) {
    const story_game *g = &GAMES[game];
    unsigned char bytes[16];
    int i;
    for (i = 0; i < g->write_count; ++i) {
        if (!mem_matches(g->writes[i].va, g->writes[i].expect, g->writes[i].length)) {
            return 0;
        }
    }
    for (i = 0; i < game_detour_count(g); ++i) {
        const story_detour *d = game_detour(g, i);
        if (d->length > (int)sizeof bytes || !mem_matches(d->va, d->expect, d->length)) {
            return 0;
        }
    }
    if (!oc_verify(game)) {
        return 0;
    }
    for (i = 0; i < g->write_count && !charges[game]; ++i) {
        if (!mem_write(g->writes[i].va, g->writes[i].replace, g->writes[i].length)) {
            install_undo(g, i, 0);
            return 0;
        }
    }
    for (i = 0; i < game_detour_count(g); ++i) {
        const story_detour *d = game_detour(g, i);
        detour_bytes(d, bytes);
        if (!mem_write(d->va, bytes, d->length)) {
            install_undo(g, charges[game] ? 0 : g->write_count, i);
            return 0;
        }
    }
    if (!oc_install(game)) {
        install_undo(g, charges[game] ? 0 : g->write_count, game_detour_count(g));
        return 0;
    }
    return 1;
}

/* "Story / Cheat Upgrades cost Tech Points" for `game`: called by the
   Origins companion before the install when the patcher's startup flag says
   so.  Ignored once the install has run (its prices are what they are). */
__declspec(dllexport) void __stdcall VvfpStoryCharge(int game) {
    if (game >= 1 && game <= 5 && install_state[game] == 0) {
        charges[game] = 1;
    }
}

/* The install alone, once: every site verified, then written; nothing
   else.  Called at game start by the Origins companion's VvfpStartup (from
   "VVFP Startup.dll", at the executable's call of WinMain), before any
   village exists, so the detours are in place for the first load-time
   catch-up.  Idempotent.  Returns whether they are in place. */
__declspec(dllexport) int __stdcall VvfpStoryArm(int game) {
    if (game < 1 || game > 5) {
        return 0;
    }
    if (install_state[game] == 0) {
        install_state[game] = install(game) ? 1 : -1;
        if (install_state[game] == 1 && game == 2) {
            /* Restore Missing Island Events' lore pages, when that row is ticked. */
            vv2_install_page_roll();
        }
    }
    return install_state[game] == 1;
}

/* Called by the Origins companion of `game` (1-5) from its own per-frame or
   menu path, outside DllMain: the install (when game start has not made it)
   and the custom titles' tick.  Returns whether the free prices and the
   Pick Island Event detour are in place. */
__declspec(dllexport) int __stdcall VvfpStoryInstall(int game) {
    static DWORD last_tick;
    DWORD now;
    if (!VvfpStoryArm(game)) {
        return 0;
    }
    /* The custom titles' tick: bind to the save slot, notice a Start Over,
       forget the titles of villagers who are gone. */
    now = GetTickCount();
    if (now - last_tick >= TICK_MS) {
        last_tick = now;
        titles_tick(game);
    }
    return 1;
}

/* Whether this game's Origins upgrades are free right now: the Origins
   companion shows 0 and charges 0 in its own prompts only when this is 1. */
__declspec(dllexport) int __stdcall VvfpStoryActive(int game) {
    return game >= 1 && game <= 5 && install_state[game] == 1 && !charges[game];
}

/* Whether the Story / Cheat Upgrades are in place (free or charged): the
   Pick Island Event, Custom Island Event and Pick Gong of Wonder Outcome
   buttons are offered while this is 1. */
static int story_installed(int game) {
    return game >= 1 && game <= 5 && install_state[game] == 1;
}

__declspec(dllexport) int __stdcall VvfpStoryInstalled(int game) {
    return story_installed(game);
}

/* What Pick Island Event, Custom Island Event and Pick Gong of Wonder
   Outcome cost in `game` now: 0, or the Island Event upgrade's price. */
__declspec(dllexport) int __stdcall VvfpStoryEventPrice(int game) {
    return story_installed(game) && charges[game] ? STORY_EVENT_PRICE : 0;
}

/* What a story purchase prompt names as its price ("0" or "30,000"). */
static const char *story_price_text(int game) {
    static char text[16];
    int price = VvfpStoryEventPrice(game);
    if (price >= 1000) {
        wsprintfA(text, "%d,%03d", price / 1000, price % 1000);
    } else {
        wsprintfA(text, "%d", price);
    }
    return text;
}

typedef int (*story_command_fn)(int game, HWND owner);

/* `command`, charged when the upgrades cost tech points: refused with a
   message while the village has fewer, and the price taken only when the
   command says an event (or outcome) is now on its way. */
static int story_charged(int game, HWND owner, story_command_fn command) {
    const ce_adapter *a = ce_adapter_for(game);
    int price = VvfpStoryEventPrice(game);
    int done;
    if (price == 0 || a == NULL) {
        return command(game, owner);
    }
    if (a->tech() < price) {
        char text[160];
        wsprintfA(text, "This costs %d,%03d tech points, and your village has %d.",
                  price / 1000, price % 1000, a->tech());
        MessageBoxA(owner, text, "Not enough tech points", MB_OK | MB_ICONINFORMATION);
        return 0;
    }
    done = command(game, owner);
    if (done) {
        a->change_tech(CE_AMOUNT_SUBTRACT, price);
    }
    return done;
}

/* ---- The chooser ----------------------------------------------------------- */

/* "Title (variant)"; a title the game itself ends with a space (The Tree
   of Life's "The Abandoned Infants ") keeps one space before the bracket. */
static void label_of(const story_event *e, char *out, size_t size) {
    int n;
    lstrcpynA(out, e->title, (int)size);
    if (e->variant != NULL && e->variant[0] != '\0') {
        n = lstrlenA(out);
        while (n > 0 && out[n - 1] == ' ') {
            out[--n] = '\0';
        }
        if ((size_t)n + (size_t)lstrlenA(e->variant) + 4 <= size) {
            wsprintfA(out + n, " (%s)", e->variant);
        }
    }
}

#include "story_outcomes_ui.inc"

/* Arms `event` for `game`: makes the island event due and remembers the
   pick.  1 on success. */
static int arm_pick(int game, const story_event *event) {
    if (!GAMES[game].arm()) {
        return 0;
    }
    pick_slot = event->slot;
    pick_game = game;
    pick_tick = STORY_TICK();
    pick_event = event;
    pick_village = story_village_now(game);
    return 1;
}

/* Called by "VVFP Save Reset.dll" (ResetDeletedTribe) when the player
   deletes a tribe or starts over: the village a queued event was for is
   gone (or replaced in the same slot), so every queued event is discarded. */
__declspec(dllexport) void __stdcall VvfpStoryVillageReset(int game, int slot) {
    (void)game;
    (void)slot;
    ++story_village_generation;
}

/* The Pick Island Event upgrade, called by the Origins companion when its
   Pick Island Event button is clicked (the companion has already refused a
   click while the Island Event row is locked).  Shows the chooser, confirms
   the 0-point purchase, and arms the pick.  Returns 1 when an event is on
   its way, 0 otherwise. */
static int story_pick_island_event(int game, HWND owner);

__declspec(dllexport) int __stdcall VvfpStoryPickIslandEvent(int game, HWND owner) {
    return story_charged(game, owner, story_pick_island_event);
}

static int story_pick_island_event(int game, HWND owner) {
    const story_game *g;
    const story_event *event;
    const oc_settings *settings;
    const char *warning;
    char label[160];
    char summary[1200];
    char message[1800];
    int chosen;
    int possible_now;
    if (!story_installed(game)) {
        return 0;
    }
    g = &GAMES[game];
    drop_lapsed_pick();
    ce_drop_lapsed();
    if (pick_slot >= 0 || ce_armed || g->island_pending()) {
        /* New Believers' Island Event and Barrel of Babies share one queue
           (either blocks both purchases); the pick shares it too. */
        MessageBoxA(owner,
                    game == 5
                        ? "An island event or a barrel of babies is already queued "
                          "and on its way.\n\nIt arrives shortly. Close this screen "
                          "and wait for it to arrive."
                        : "An island event is already queued and on its way.\n\n"
                          "It arrives shortly. Close this screen and wait for it to arrive.",
                    "Not right now", MB_OK | MB_ICONINFORMATION | MB_TOPMOST | MB_SETFOREGROUND);
        return 0;
    }
    if (last_failed_event != NULL) {
        label_of(last_failed_event, label, sizeof label);
        if (last_failed_lapsed) {
            wsprintfA(message,
                      "The last island event you picked, %s, did not happen within "
                      "ten minutes, so it was cancelled.", label);
        } else {
            wsprintfA(message,
                      "The last island event you picked, %s, could not happen when it "
                      "was due (it needs %s), so the island event the game chose "
                      "happened instead.",
                      label, last_failed_event->requires);
        }
        MessageBoxA(owner, message, "Pick Island Event",
                    MB_OK | MB_ICONINFORMATION | MB_TOPMOST | MB_SETFOREGROUND);
        last_failed_event = NULL;
    }
    chosen = chooser_run(game, g, owner);
    if (chosen < 0) {
        return 0;
    }
    event = &g->events[chosen];
    settings = &chooser.settings[chosen];
    label_of(event, label, sizeof label);
    chooser_summary(chosen, summary, sizeof summary);
    wsprintfA(message,
              "Do you want to buy Pick Island Event (%s) for %s tech points?%s%s\r\n\r\n"
              "Press OK to confirm, or Cancel.", label, story_price_text(game),
              summary[0] ? "\r\n" : "", summary);
    if (MessageBoxA(owner, message, "Origins Upgrades",
                    MB_OKCANCEL | MB_ICONQUESTION | MB_TOPMOST | MB_SETFOREGROUND) != IDOK) {
        return 0;
    }
    warning = chooser_warning(chosen);
    if (warning != NULL
        && MessageBoxA(owner, warning, "Pick Island Event",
                       MB_OKCANCEL | MB_ICONWARNING | MB_DEFBUTTON2 | MB_TOPMOST | MB_SETFOREGROUND)
               != IDOK) {
        return 0;
    }
    /* The village may have moved on while the boxes were open. */
    possible_now = g->possible(event) || (settings->unlocked && oc_unlock_possible(game, event));
    if (ce_armed || g->island_pending() || !possible_now || !arm_pick(game, event)) {
        MessageBoxA(owner, "That island event can not happen right now. No tech points have been deducted.",
                    "Origins Upgrades", MB_OK | MB_ICONINFORMATION | MB_TOPMOST | MB_SETFOREGROUND);
        return 0;
    }
    oc_arm(game, event->slot, settings);
    wsprintfA(message, "%s is on its way.", label);
    MessageBoxA(owner, message, "Origins Upgrades",
                MB_OK | MB_ICONINFORMATION | MB_TOPMOST | MB_SETFOREGROUND);
    return 1;
}

/* Whether a pick or a custom event is armed and not yet delivered. */
__declspec(dllexport) int __stdcall VvfpStoryPickPending(int game) {
    drop_lapsed_pick();
    return (pick_slot >= 0 && pick_game == game) || ce_pending(game);
}

#include "story_custom_ui.inc"

BOOL WINAPI DllMain(HINSTANCE instance, DWORD reason, LPVOID reserved) {
    (void)reserved;
    if (reason == DLL_PROCESS_ATTACH) {
        module_instance = instance;
        DisableThreadLibraryCalls(instance);
    }
    return TRUE;
}

#ifdef VVFP_TEST
/* ---- Test build only ------------------------------------------------------- */

/* Site `index` of `game`: its address, the bytes verified there and the bytes
   written.  Returns the length, or 0 past the end.  Detours follow the
   writes; their written bytes are computed for this load of the DLL. */
__declspec(dllexport) int __stdcall VvfpStoryProbeSite(int game, int index, unsigned int *va,
                                                        unsigned char *expect,
                                                        unsigned char *replace) {
    const story_game *g;
    if (game < 1 || game > 5) {
        return 0;
    }
    g = &GAMES[game];
    if (index < g->write_count) {
        *va = g->writes[index].va;
        memcpy(expect, g->writes[index].expect, (size_t)g->writes[index].length);
        memcpy(replace, g->writes[index].replace, (size_t)g->writes[index].length);
        return g->writes[index].length;
    }
    index -= g->write_count;
    if (index < game_detour_count(g)) {
        const story_detour *d = game_detour(g, index);
        *va = d->va;
        memcpy(expect, d->expect, (size_t)d->length);
        detour_bytes(d, replace);
        return d->length;
    }
    index -= game_detour_count(g);
    return oc_probe_site(game, index, va, expect, replace);
}

/* Arms a pick by its position in this game's event table without any
   dialog, at test tick `tick`.  Returns the game's index of the event. */
__declspec(dllexport) int __stdcall VvfpStoryProbeArm(int game, int position, DWORD tick) {
    const story_game *g;
    if (game < 1 || game > 5) {
        return -1;
    }
    g = &GAMES[game];
    if (position < 0 || position >= g->event_count) {
        return -1;
    }
    test_tick = tick;
    install_state[game] = 1;
    if (!arm_pick(game, &g->events[position])) {
        return -1;
    }
    return g->events[position].slot;
}

/* Arms a pick WITHOUT making the island event due (the delivery tests drive
   the selector directly). */
__declspec(dllexport) int __stdcall VvfpStoryProbeSetPick(int game, int position, DWORD tick) {
    const story_game *g;
    if (game < 1 || game > 5) {
        return -1;
    }
    g = &GAMES[game];
    if (position < 0 || position >= g->event_count) {
        return -1;
    }
    pick_slot = g->events[position].slot;
    pick_game = game;
    pick_tick = tick;
    pick_event = &g->events[position];
    pick_village = story_village_now(game);
    return pick_slot;
}

/* The Lost Children: point Restore Missing Island Events' page roll at the
   companion as VvfpStoryInstall does (the tests arm without installing).
   Returns whether it is installed. */
__declspec(dllexport) int __stdcall VvfpStoryProbeInstallPageRoll(void) {
    vv2_install_page_roll();
    return vv2_page_installed;
}

/* Make the n-th memory write of the next install fail (-1 = none). */
__declspec(dllexport) void __stdcall VvfpStoryProbeFailWrite(int n) {
    test_fail_write = n;
}

/* The Custom Island Event's quicker delivery (story_fast_delivery.inc),
   driven by a scripted picker: `draws` are the picker's answers in turn,
   `fits[i]` whether draw i passes the trigger's age check.  Returns the
   villager handed back; *calls the times the picker was asked. */
typedef struct { const int *draws; const int *fits; int count; int at; } probe_pick;
static int probe_draw(void *ctx) {
    probe_pick *p = (probe_pick *)ctx;
    int i = p->at < p->count ? p->at : p->count - 1;
    ++p->at;
    return p->draws[i];
}
static int probe_fits(void *ctx, int drawn) {
    probe_pick *p = (probe_pick *)ctx;
    int i = p->at - 1 < p->count ? p->at - 1 : p->count - 1;
    (void)drawn;
    return p->fits[i];
}
__declspec(dllexport) int __stdcall VvfpStoryProbeFastPick(const int *draws, const int *fits,
                                                           int count, int none, int *calls) {
    probe_pick p = { draws, fits, count, 0 };
    int drawn = ce_fast_pick(probe_draw, probe_fits, none, &p);
    *calls = p.at;
    return drawn;
}

__declspec(dllexport) void __stdcall VvfpStoryProbeSetTick(DWORD tick) {
    test_tick = tick;
}

__declspec(dllexport) int __stdcall VvfpStoryProbePending(int game) {
    return GAMES[game].island_pending();
}

__declspec(dllexport) int __stdcall VvfpStoryProbePossible(int game, int position) {
    return GAMES[game].possible(&GAMES[game].events[position]);
}

__declspec(dllexport) int __stdcall VvfpStoryProbeArmedSlot(void) {
    return pick_slot;
}

/* Arms `event` for `game` exactly as the dialog's purchase does, without
   any dialog or check, at test tick `tick`.  1 on success. */
__declspec(dllexport) int __stdcall VvfpStoryProbeQueueCustom(int game, const ce_event *event,
                                                              DWORD tick) {
    if (game < 1 || game > 5) {
        return 0;
    }
    test_tick = tick;
    install_state[game] = 1;
    return ce_arm_with(game, event, NULL);
}

/* Arms `event` WITHOUT making the island event due (the delivery tests
   drive the game's own code directly). */
__declspec(dllexport) int __stdcall VvfpStoryProbeSetCustom(int game, const ce_event *event,
                                                            DWORD tick) {
    ce_armed_event = *event;
    ce_armed_event.game = game;
    ce_armed_is_choice = 0;
    ce_armed = 1;
    (void)tick;                       /* a custom event never lapses with time */
    ce_armed_village = story_village_now(game);
    return 1;
}

__declspec(dllexport) int __stdcall VvfpStoryProbeCustomPending(int game) {
    return ce_pending(game);
}

__declspec(dllexport) void __stdcall VvfpStoryProbeResult(ce_result *out) {
    *out = ce_last_result;
}

/* The engine on its own: apply `event` now and compose the popup text. */
__declspec(dllexport) int __stdcall VvfpStoryProbeApply(int game, const ce_event *event,
                                                        ce_result *result, char *text, int size) {
    const ce_adapter *a = ce_adapter_for(game);
    if (a == NULL) {
        return 0;
    }
    ce_apply(a, event, result);
    return ce_compose(a, event, result, text, size);
}

/* Why `event` can not be queued in `game` now (a string), or NULL. */
__declspec(dllexport) const char *__stdcall VvfpStoryProbeRefusal(int game, const ce_event *event) {
    return ce_refusal(game, event);
}

/* The dialog's target list: the roster with `picked` (per roster position)
   and `toggles` combined; writes record indices, returns the count. */
__declspec(dllexport) int __stdcall VvfpStoryProbeTargets(int game, const unsigned char *picked,
                                                          unsigned int toggles, int *out, int cap) {
    static story_member roster[UI_ROSTER_MAX];
    const ce_adapter *a = ce_adapter_for(game);
    int n;
    if (a == NULL) {
        return -1;
    }
    n = ce_picker_roster(a, roster, UI_ROSTER_MAX);
    return story_resolve_targets(roster, n, picked, toggles, a->adult_age, out, cap);
}

/* The list's role for record `index`: its STORY_KIND_*, the label copied to
   `words` ("" for none). */
__declspec(dllexport) int __stdcall VvfpStoryProbeRole(int game, int index, char *words, int size) {
    const ce_adapter *a = ce_adapter_for(game);
    const unsigned char *record;
    const char *said = NULL;
    int kind;
    int i = 0;
    if (a == NULL || size < 1 || (record = a->record(index)) == NULL) {
        return -1;
    }
    kind = ce_role(a, record, &said);
    for (; said != NULL && said[i] != '\0' && i < size - 1; ++i) {
        words[i] = said[i];
    }
    words[i] = '\0';
    return kind;
}

/* The dialog's merge of one villager's changes into an event. */
__declspec(dllexport) int __stdcall VvfpStoryProbeMerge(ce_event *event, const ce_change *change,
                                                        int index, unsigned int fingerprint) {
    return ce_merge(event, change, index, fingerprint);
}

__declspec(dllexport) void __stdcall VvfpStoryProbeInitChange(ce_change *change) {
    ce_change_init(change);
}

/* Custom titles without the file: bind the table to `slot` as loaded, with
   no entries; then VvfpStoryProbeTitleSet adds one without publishing. */
__declspec(dllexport) void __stdcall VvfpStoryProbeTitlesLoaded(int game, int slot, const char *path) {
    titles_forget();
    titles.game = game;
    titles.slot = slot;
    titles.loaded = 1;
    titles.file_present = 0;
    lstrcpynA(titles.path, path, MAX_PATH);
    vv_sidecar_gate_bind(&titles.gate, game * 16 + slot);
    lstrcpynA(titles.gate.path, path, MAX_PATH);
    titles.gate.state = VV_SIDECAR_SETTLED;     /* as a load that found no file */
}

__declspec(dllexport) int __stdcall VvfpStoryProbeTitleSet(int game, int index, const char *text) {
    const unsigned char *record = story_record(game, index);
    if (record == NULL || titles.count >= VV_TITLES_MAX) {
        return 0;
    }
    titles.entries[titles.count].index = (unsigned int)index;
    titles.entries[titles.count].fingerprint = story_title_identity(game, record);
    lstrcpynA(titles.entries[titles.count].title, text, VV_TITLE_BYTES);
    titles.seen[titles.count] = 0;
    ++titles.count;
    return 1;
}

__declspec(dllexport) const char *__stdcall VvfpStoryProbeTitleOf(int game, const unsigned char *record) {
    return titles_lookup(game, record);
}

__declspec(dllexport) int __stdcall VvfpStoryProbeTitleCount(void) {
    return titles.count;
}

/* The layout the tests pack events in: sizes of ce_event, ce_spawn,
   ce_change, ce_result, then the offsets of ce_event.spawns, .change_count
   and .changes. */
__declspec(dllexport) void __stdcall VvfpStoryProbeSizes(int *out) {
    out[0] = (int)sizeof(ce_event);
    out[1] = (int)sizeof(ce_spawn);
    out[2] = (int)sizeof(ce_change);
    out[3] = (int)sizeof(ce_result);
    out[4] = (int)offsetof(ce_event, spawns);
    out[5] = (int)offsetof(ce_event, change_count);
    out[6] = (int)offsetof(ce_event, changes);
}

__declspec(dllexport) const void *__stdcall VvfpStoryProbeObject(void) {
    return &ce_object;
}

/* ---- Two-choice events ---- */

/* The layout the tests pack choices in: sizeof ce_choice, sizeof
   ce_outcome, the offsets of .labels, .outcome_count and .outcomes,
   CE_BUTTON_BYTES, CE_MAX_OUTCOMES, CE_MAX_CHANCE, CE_LABEL_DEFAULT_WIDTH,
   offsetof(ce_outcome, effects). */
__declspec(dllexport) void __stdcall VvfpStoryProbeChoiceSizes(int *out) {
    out[0] = (int)sizeof(ce_choice);
    out[1] = (int)sizeof(ce_outcome);
    out[2] = (int)offsetof(ce_choice, labels);
    out[3] = (int)offsetof(ce_choice, outcome_count);
    out[4] = (int)offsetof(ce_choice, outcomes);
    out[5] = CE_BUTTON_BYTES;
    out[6] = CE_MAX_OUTCOMES;
    out[7] = CE_MAX_CHANCE;
    out[8] = CE_LABEL_DEFAULT_WIDTH;
    out[9] = (int)offsetof(ce_outcome, effects);
}

/* The capabilities of `game`'s adapter. */
__declspec(dllexport) unsigned int __stdcall VvfpStoryProbeCaps(int game) {
    const ce_adapter *a = ce_adapter_for(game);
    return a != NULL ? a->caps : 0;
}

/* Every game may ask a question (1) or only those whose adapter has
   CAP_CHOICE (0): the engine is tested apart from the hooks. */
__declspec(dllexport) void __stdcall VvfpStoryProbeChoiceCap(int on) {
    test_choice_cap = on;
}

/* The next roll is `roll` (modulo the chances' total), -1 = the real source. */
__declspec(dllexport) void __stdcall VvfpStoryProbeSetRoll(int roll) {
    test_roll = roll;
}

/* The pure weighted pick: which of `count` outcomes with `chances` the
   roll value `roll` (0..sum-1) selects. */
__declspec(dllexport) int __stdcall VvfpStoryProbeRollIndex(const int *chances, int count, int roll) {
    return ce_roll_index(chances, count, roll);
}

/* `times` rolls of `button` of `choice` in `game` through the real random
   source, counting each outcome in counts[0..3]. */
__declspec(dllexport) void __stdcall VvfpStoryProbeRollMany(int game, const ce_choice *choice, int button,
                                                            int times, int *counts) {
    const ce_adapter *a = ce_adapter_for(game);
    int i;
    for (i = 0; i < CE_MAX_OUTCOMES; ++i) {
        counts[i] = 0;
    }
    for (i = 0; i < times && a != NULL; ++i) {
        int k = ce_choice_roll(a, choice, button);
        if (k >= 0 && k < CE_MAX_OUTCOMES) {
            ++counts[k];
        }
    }
}

/* Why the two-choice event cannot be queued in `game` now, or NULL. */
__declspec(dllexport) const char *__stdcall VvfpStoryProbeChoiceRefusal(int game, const ce_event *event,
                                                                        const ce_choice *choice) {
    return ce_choice_refusal(game, event, choice);
}

/* Arms the two-choice event exactly as the purchase does (the island event
   made due), at test tick `tick`.  1 on success. */
__declspec(dllexport) int __stdcall VvfpStoryProbeQueueChoice(int game, const ce_event *event,
                                                              const ce_choice *choice, DWORD tick) {
    if (game < 1 || game > 5) {
        return 0;
    }
    test_tick = tick;
    install_state[game] = 1;
    return ce_arm_with(game, event, choice);
}

/* Arms the two-choice event WITHOUT making the island event due (the
   engine tests drive the entry points directly), as ce_arm_with stores it. */
__declspec(dllexport) int __stdcall VvfpStoryProbeSetChoice(int game, const ce_event *event,
                                                            const ce_choice *choice, DWORD tick) {
    ce_armed_event = *event;
    ce_armed_event.game = game;
    ce_store_choice(game, choice);
    ce_armed = 1;
    test_tick = tick;
    ce_armed_village = story_village_now(game);
    return 1;
}

/* The hooks' entry points. */
__declspec(dllexport) int __stdcall VvfpStoryProbeChoiceBegin(int game, char *text, int size) {
    return ce_choice_begin(game, text, size);
}

__declspec(dllexport) const char *__stdcall VvfpStoryProbeChoiceLabel(int game, int button) {
    return ce_choice_label(game, button);
}

__declspec(dllexport) const char *__stdcall VvfpStoryProbeChoiceTitle(int game) {
    return ce_choice_title(game);
}

__declspec(dllexport) int __stdcall VvfpStoryProbeChoiceResolve(int game, int button, char *text, int size) {
    return ce_choice_resolve(game, button, text, size);
}

/* ce_choice_pending, ce_choice_asked, and the last resolved button and
   outcome, into out[0..3]. */
__declspec(dllexport) void __stdcall VvfpStoryProbeChoiceState(int game, int *out) {
    out[0] = ce_choice_pending(game);
    out[1] = ce_choice_asked(game);
    out[2] = ce_last_button;
    out[3] = ce_last_outcome;
}

/* The plain delivery the VV1 / VV2 hooks call (a two-choice event must not
   go through it). */
__declspec(dllexport) int __stdcall VvfpStoryProbeDeliver(int game, char *text, int size) {
    return ce_deliver(game, text, size);
}
#endif
