/* VVFP Story Upgrades -- the companion of the "Story / Cheat Upgrades" rows
   (all five games, default-off, requires the Origins upgrades).

   The owner: "Adds optional tools intended for custom stories, experiments,
   sandbox play, and cheats.  ...  When enabled, all Origins Upgrades cost 0
   Tech Points.  Also adds ... Pick Island Event -- Allows the player to
   directly choose which stock Island Event occurs instead of relying on
   random selection."

   WHAT THIS COMPANION DOES.

   1. Free Origins upgrades.  Every place the Origins payload of the
      executable compares the tech-point balance with a price, deducts a
      price, refunds a price or shows a price is listed in story_tables.h
      (generated by scripts/build_story_cheat_upgrades_features.py, which
      checks every listed byte against the executable the patcher renders, in
      all three population modes).  VvfpStoryInstall verifies EVERY listed
      site first and writes nothing unless all of them hold exactly the bytes
      the Origins payload put there; then it writes the zero-cost bytes.  So
      the feature is all or nothing: a build whose Origins bytes differ gets
      no change at all, and the Origins companion keeps showing and charging
      the normal prices (it asks VvfpStoryActive before showing 0).
      A price of 0 keeps every lock: `cmp balance, 0; jb` never refuses, and
      every pending, capacity and "nothing to change" refusal still runs.

   2. Pick Island Event.  The player picks one of the game's own island
      events from a plain dialog.  The pick then makes the island event due
      exactly as the Origins "Island Event" purchase does (the same fields,
      so the same pending lock), and when the game's own scheduler fires that
      event, a detour at the point where the game has just chosen WHICH event
      to run replaces the random choice with the picked one -- and only if
      the game's own condition for that event holds at that moment.  The
      event is then created, shown and resolved by the game's own code, with
      its own random outcomes, choices and amounts; nothing about the event
      itself is emulated here.

   Installed at run time by VvfpStoryInstall(game) from the Origins
   companion (once it runs in the game process, outside DllMain).  The stock
   or Origins bytes at every site are verified first. */
#include <windows.h>
#include <string.h>
#include <intrin.h>

#include "story_tables.h"

enum {
    IDD_PICK = 301,
    IDC_PICK_LIST = 3001,
    IDC_PICK_DESC = 3002
};

#define PICK_TIMEOUT_MS (10u * 60u * 1000u)   /* an undelivered pick lapses after 10 minutes */
#define CAN_FIRE_TRIES 16                      /* see can_fire_with_retries */

static HINSTANCE module_instance;
static int install_state[6];      /* 0 = not tried, 1 = active, -1 = refused */

/* The armed pick: the game's own index of the chosen event (-1 = none),
   when it was armed, and the table entry it came from. */
static int pick_slot = -1;
static int pick_game;
static DWORD pick_tick;
static const story_event *pick_event;
/* The outcome of the last pick, shown the next time the chooser opens when
   the game could not run it. */
static const story_event *last_failed_event;

#ifdef VVFP_TEST
/* Counters the tests read.  Compiled only into the TEST build. */
struct vvfp_story_stats {
    int delivered;      /* a picked event replaced the game's random choice */
    int refused;        /* the picked event's own condition did not hold */
    int lapsed;         /* an armed pick was dropped as too old */
};
__declspec(dllexport) struct vvfp_story_stats VvfpStoryStats = { 0 };
#define STORY_COUNT(field) (++VvfpStoryStats.field)
static DWORD test_tick;
#define STORY_TICK() (test_tick)
#else
#define STORY_COUNT(field) ((void)0)
#define STORY_TICK() (GetTickCount())
#endif

/* ---- Memory ---------------------------------------------------------------- */

static int mem_readable(unsigned int va, int length) {
    MEMORY_BASIC_INFORMATION info;
    const void *at = (const void *)(uintptr_t)va;
    if (VirtualQuery(at, &info, sizeof(info)) != sizeof(info) || info.State != MEM_COMMIT
        || (info.Protect & (PAGE_NOACCESS | PAGE_GUARD)) != 0) {
        return 0;
    }
    return (uintptr_t)at + (unsigned int)length
           <= (uintptr_t)info.BaseAddress + info.RegionSize;
}

static int mem_matches(unsigned int va, const unsigned char *bytes, int length) {
    if (!mem_readable(va, length)) {
        return 0;
    }
    return memcmp((const void *)(uintptr_t)va, bytes, (size_t)length) == 0;
}

static int mem_write(unsigned int va, const unsigned char *bytes, int length) {
    DWORD old;
    void *at = (void *)(uintptr_t)va;
    if (!VirtualProtect(at, (SIZE_T)length, PAGE_EXECUTE_READWRITE, &old)) {
        return 0;
    }
    memcpy(at, bytes, (size_t)length);
    VirtualProtect(at, (SIZE_T)length, old, &old);
    FlushInstructionCache(GetCurrentProcess(), at, (SIZE_T)length);
    return 1;
}

static unsigned int read_u32(unsigned int va) {
    return *(volatile unsigned int *)(uintptr_t)va;
}

/* The bytes a detour writes at its site: a jmp (or, for a call site, a call)
   to the stub, padded with nops. */
static void detour_bytes(const story_detour *d, unsigned char *out) {
    unsigned int rel = (unsigned int)((uintptr_t)d->stub - ((uintptr_t)d->va + 5));
    int i;
    out[0] = d->is_call ? 0xE8 : 0xE9;
    memcpy(out + 1, &rel, 4);
    for (i = 5; i < d->length; ++i) {
        out[i] = 0x90;
    }
}

/* ---- Per-game event code -------------------------------------------------- */

typedef char (__fastcall *can_fire_fn)(void *self, void *unused_edx);
typedef void *(__cdecl *getter_fn)(void);

/* The game's own condition for an event object (vtable slot 1, thiscall, no
   arguments).  Several conditions roll the game's random generator or pick
   the villager the event will be about (stored in the object), so a false
   answer can be random rather than final: it is asked a few times before the
   event is called impossible.  A true answer leaves the object exactly as
   the game's own selector would have left it before running the event. */
static int can_fire_with_retries(void *object) {
    int i;
    for (i = 0; i < CAN_FIRE_TRIES; ++i) {
        can_fire_fn can_fire = (can_fire_fn)(*(void ***)object)[1];
        if (can_fire(object, NULL)) {
            return 1;
        }
    }
    return 0;
}

/* An armed pick that the game has not run within PICK_TIMEOUT_MS is
   dropped (so a pick can never carry over into a village loaded much later);
   the next chooser says so.  Returns 1 when a pick was dropped. */
static int last_failed_lapsed;

static int drop_lapsed_pick(void) {
    if (pick_slot >= 0 && STORY_TICK() - pick_tick > PICK_TIMEOUT_MS) {
        pick_slot = -1;
        last_failed_event = pick_event;
        last_failed_lapsed = 1;
        STORY_COUNT(lapsed);
        return 1;
    }
    return 0;
}

/* Takes the armed pick for `game` (and clears it): the game's index of the
   event, or -1. */
static int take_pick(int game) {
    int slot;
    if (drop_lapsed_pick()) {
        return -1;
    }
    slot = pick_slot;
    if (slot < 0 || pick_game != game) {
        return -1;
    }
    pick_slot = -1;
    return slot;
}

/* For VV3, VV4 and VV5: the selector has just chosen `current`; return the
   index the selector should use.  `table` is the game's event-object array. */
static int choose_from_table(int game, unsigned int table, int current) {
    void *object;
    const story_event *event = pick_event;
    int slot = take_pick(game);
    if (slot < 0) {
        return current;
    }
    object = *(void **)(uintptr_t)(table + 4u * (unsigned int)slot);
    if (object != NULL && can_fire_with_retries(object)) {
        STORY_COUNT(delivered);
        last_failed_event = NULL;
        return slot;
    }
    STORY_COUNT(refused);
    last_failed_event = event;
    last_failed_lapsed = 0;
    return current;
}

/* The Secret City.  0x419BDB `mov edx, [esi*4 + 0x4B3C78]` is where the
   selector 0x419B30 has settled on `esi` (after its own random pick and its
   rescue override) and is about to build the event dialog.

   The Origins Barrel of Babies delivers its barrel by calling the same
   selector with EVERY slot pointing at the barrel object (0x47B3E0); a pick
   is never consumed there, because what would run is the barrel, not the
   pick.  All slots equal is that state and never the game's own. */
static int __cdecl vv3_choose(int current) {
    if (read_u32(VV3_EVENT_TABLE + 4) == read_u32(VV3_EVENT_TABLE + 8)) {
        return current;
    }
    return choose_from_table(3, VV3_EVENT_TABLE, current);
}

__declspec(naked) static void vv3_stub(void) {
    __asm {
        pushad
        push esi
        call vv3_choose
        add esp, 4
        mov dword ptr [esp + 4], eax      /* the saved ESI in the pushad frame */
        popad
        mov edx, dword ptr [esi * 4 + 0x4B3C78]
        push 0x419BE2
        ret
    }
}

/* The Tree of Life.  0x4180F7 `mov eax, [esi*4 + 0x4CCA28]`: the selector
   0x418000 has settled on `esi` (after the random pick and the rescue
   override) and is about to present it.  The Origins Barrel delivers through
   0x418190 instead, which never passes here. */
static int __cdecl vv4_choose(int current) {
    return choose_from_table(4, VV4_EVENT_TABLE, current);
}

__declspec(naked) static void vv4_stub(void) {
    __asm {
        pushad
        push esi
        call vv4_choose
        add esp, 4
        mov dword ptr [esp + 4], eax
        popad
        mov eax, dword ptr [esi * 4 + 0x4CCA28]
        push 0x4180FE
        ret
    }
}

/* New Believers.  0x41895B `mov eax, [esi*4 + 0x4DC850]`: after the Origins
   selector stub (0x41890F, the purchased Barrel) and the stock Chutes Without
   Ladders override, so nothing later can replace the pick. */
static int __cdecl vv5_choose(int current) {
    return choose_from_table(5, VV5_EVENT_TABLE, current);
}

__declspec(naked) static void vv5_stub(void) {
    __asm {
        pushad
        push esi
        call vv5_choose
        add esp, 4
        mov dword ptr [esp + 4], eax
        popad
        mov eax, dword ptr [esi * 4 + 0x4DC850]
        push 0x418962
        ret
    }
}

/* Each game's clock (seconds), thiscall on the world object. */
typedef int (__fastcall *clock_fn)(void *self, void *unused_edx);

#include "story_vv1.inc"
#include "story_vv2.inc"

/* ---- Making the island event due ------------------------------------------ */

/* Each game: is an island event already on its way (the Island Event row's
   own lock), and make one due exactly as the Origins Island Event purchase
   does.  Returns 1 on success. */
static int vv3_island_pending(void) {
    return *(volatile unsigned char *)(uintptr_t)VV3_ISLAND_FLAG != 0;
}

static int vv3_arm(void) {
    void *manager = *(void **)(uintptr_t)VV3_MANAGER_GLOBAL;
    void (__fastcall *queue_arm_island)(void *, void *) =
        (void (__fastcall *)(void *, void *))(uintptr_t)VV3_QUEUE_ARM_ISLAND;
    if (manager == NULL) {
        return 0;
    }
    queue_arm_island(manager, NULL);   /* the Island Event purchase's own helper */
    return 1;
}

static int vv4_island_pending(void) {
    unsigned char *world = *(unsigned char **)(uintptr_t)VV4_WORLD_GLOBAL;
    unsigned int countdown;
    if (world == NULL) {
        return 1;
    }
    countdown = *(unsigned int *)(world + VV4_COUNTDOWN);
    if (*(volatile unsigned char *)(uintptr_t)VV4_ISLAND_TOKEN != 0
        && (countdown == read_u32(VV4_ISLAND_STAMP)
            || *(volatile unsigned char *)(uintptr_t)VV4_BARREL_ARMED != 0)) {
        return 1;
    }
    if (countdown == 0) {
        return 1;
    }
    return countdown - (unsigned int)((clock_fn)(uintptr_t)VV4_CLOCK)(world, NULL) <= 5u;
}

static int vv4_arm(void) {
    unsigned char *world = *(unsigned char **)(uintptr_t)VV4_WORLD_GLOBAL;
    unsigned int due;
    if (world == NULL) {
        return 0;
    }
    due = (unsigned int)((clock_fn)(uintptr_t)VV4_CLOCK)(world, NULL) + 5u;
    *(unsigned int *)(world + VV4_COUNTDOWN) = due;
    *(volatile unsigned char *)(uintptr_t)VV4_ISLAND_TOKEN = 1;
    *(volatile unsigned int *)(uintptr_t)VV4_ISLAND_STAMP = due;
    return 1;
}

static int vv5_island_pending(void) {
    return (read_u32(VV5_PURCHASE_FLAGS) & 0x3Cu) != 0;
}

static int vv5_arm(void) {
    unsigned char *world = *(unsigned char **)(uintptr_t)VV5_WORLD_GLOBAL;
    if (world == NULL) {
        return 0;
    }
    *(unsigned int *)(world + VV5_COUNTDOWN) = 0;
    *(volatile unsigned int *)(uintptr_t)VV5_PURCHASE_FLAGS |= 0x10u;
    return 1;
}

/* Whether the game's own condition for an event holds right now.  VV3-VV5:
   the event object's own condition, through the game's own event table
   (built by the game's own getter if no event has run yet this session). */
static int table_event_possible(unsigned int table, getter_fn getter, int slot) {
    void *object = *(void **)(uintptr_t)(table + 4u * (unsigned int)slot);
    if (object == NULL) {
        getter();
        object = *(void **)(uintptr_t)(table + 4u * (unsigned int)slot);
    }
    return object != NULL && can_fire_with_retries(object);
}

static int vv3_possible(const story_event *e) {
    return table_event_possible(VV3_EVENT_TABLE, (getter_fn)(uintptr_t)VV3_EVENT_GETTER, e->slot);
}

static int vv4_possible(const story_event *e) {
    return table_event_possible(VV4_EVENT_TABLE, (getter_fn)(uintptr_t)VV4_EVENT_GETTER, e->slot);
}

static int vv5_possible(const story_event *e) {
    return table_event_possible(VV5_EVENT_TABLE, (getter_fn)(uintptr_t)VV5_EVENT_GETTER, e->slot);
}

/* ---- The per-game table ---------------------------------------------------- */

typedef struct {
    const story_write *writes;
    int write_count;
    const story_detour *detours;
    int detour_count;
    const story_event *events;
    int event_count;
    int (*possible)(const story_event *event);
    int (*island_pending)(void);
    int (*arm)(void);
} story_game;

static story_detour vv3_detours[] = {
    { VV3_PICK_SITE, 7, VV3_PICK_SITE_BYTES, 0, (void *)vv3_stub },
};
static story_detour vv4_detours[] = {
    { VV4_PICK_SITE, 7, VV4_PICK_SITE_BYTES, 0, (void *)vv4_stub },
};
static story_detour vv5_detours[] = {
    { VV5_PICK_SITE, 7, VV5_PICK_SITE_BYTES, 0, (void *)vv5_stub },
};

static const story_game GAMES[6] = {
    { 0 },
    { VV1_WRITES, VV1_WRITE_COUNT, vv1_detours, sizeof vv1_detours / sizeof vv1_detours[0],
      VV1_EVENTS, VV1_EVENT_COUNT, vv1_possible, vv1_island_pending, vv1_arm },
    { VV2_WRITES, VV2_WRITE_COUNT, vv2_detours, sizeof vv2_detours / sizeof vv2_detours[0],
      VV2_EVENTS, VV2_EVENT_COUNT, vv2_possible, vv2_island_pending, vv2_arm },
    { VV3_WRITES, VV3_WRITE_COUNT, vv3_detours, 1,
      VV3_EVENTS, VV3_EVENT_COUNT, vv3_possible, vv3_island_pending, vv3_arm },
    { VV4_WRITES, VV4_WRITE_COUNT, vv4_detours, 1,
      VV4_EVENTS, VV4_EVENT_COUNT, vv4_possible, vv4_island_pending, vv4_arm },
    { VV5_WRITES, VV5_WRITE_COUNT, vv5_detours, 1,
      VV5_EVENTS, VV5_EVENT_COUNT, vv5_possible, vv5_island_pending, vv5_arm },
};

/* ---- Installing ------------------------------------------------------------ */

/* Verify every site of this game, then write every one -- or write nothing. */
static int install(int game) {
    const story_game *g = &GAMES[game];
    unsigned char bytes[16];
    int i;
    for (i = 0; i < g->write_count; ++i) {
        if (!mem_matches(g->writes[i].va, g->writes[i].expect, g->writes[i].length)) {
            return 0;
        }
    }
    for (i = 0; i < g->detour_count; ++i) {
        if (g->detours[i].length > (int)sizeof bytes
            || !mem_matches(g->detours[i].va, g->detours[i].expect, g->detours[i].length)) {
            return 0;
        }
    }
    for (i = 0; i < g->write_count; ++i) {
        if (!mem_write(g->writes[i].va, g->writes[i].replace, g->writes[i].length)) {
            return 0;
        }
    }
    for (i = 0; i < g->detour_count; ++i) {
        detour_bytes(&g->detours[i], bytes);
        if (!mem_write(g->detours[i].va, bytes, g->detours[i].length)) {
            return 0;
        }
    }
    return 1;
}

/* Called by the Origins companion of `game` (1-5) from its own per-frame or
   menu path, outside DllMain.  Idempotent.  Returns whether the free prices
   and the Pick Island Event detour are in place. */
__declspec(dllexport) int __stdcall VvfpStoryInstall(int game) {
    if (game < 1 || game > 5) {
        return 0;
    }
    if (install_state[game] == 0) {
        install_state[game] = install(game) ? 1 : -1;
    }
    return install_state[game] == 1;
}

/* Whether this game's Origins upgrades are free right now: the Origins
   companion shows 0 and charges 0 in its own prompts only when this is 1. */
__declspec(dllexport) int __stdcall VvfpStoryActive(int game) {
    return game >= 1 && game <= 5 && install_state[game] == 1;
}

/* ---- The chooser ----------------------------------------------------------- */

static struct {
    const story_game *game;
    int possible[STORY_MAX_EVENTS];
    int chosen;
} chooser;

static void label_of(const story_event *e, char *out, size_t size) {
    if (e->variant != NULL && e->variant[0] != '\0') {
        wsprintfA(out, "%s (%s)", e->title, e->variant);
    } else {
        lstrcpynA(out, e->title, (int)size);
    }
}

static void chooser_show(HWND window) {
    int sel = (int)SendDlgItemMessageA(window, IDC_PICK_LIST, LB_GETCURSEL, 0, 0);
    int index;
    char text[512];
    if (sel < 0) {
        SetDlgItemTextA(window, IDC_PICK_DESC, "");
        EnableWindow(GetDlgItem(window, IDOK), FALSE);
        return;
    }
    index = (int)SendDlgItemMessageA(window, IDC_PICK_LIST, LB_GETITEMDATA, (WPARAM)sel, 0);
    if (chooser.possible[index]) {
        lstrcpynA(text, chooser.game->events[index].description, sizeof text);
    } else {
        wsprintfA(text, "%s\r\n\r\nNot possible right now: %s",
                  chooser.game->events[index].description,
                  chooser.game->events[index].requires);
    }
    SetDlgItemTextA(window, IDC_PICK_DESC, text);
    EnableWindow(GetDlgItem(window, IDOK), chooser.possible[index]);
}

static INT_PTR CALLBACK chooser_dialog(HWND window, UINT message, WPARAM wparam, LPARAM lparam) {
    (void)lparam;
    if (message == WM_INITDIALOG) {
        int i;
        char label[160];
        for (i = 0; i < chooser.game->event_count; ++i) {
            int row;
            label_of(&chooser.game->events[i], label, sizeof label);
            if (!chooser.possible[i]) {
                lstrcatA(label, " - not possible right now");
            }
            row = (int)SendDlgItemMessageA(window, IDC_PICK_LIST, LB_ADDSTRING, 0, (LPARAM)label);
            SendDlgItemMessageA(window, IDC_PICK_LIST, LB_SETITEMDATA, (WPARAM)row, (LPARAM)i);
        }
        chooser_show(window);
        return TRUE;
    }
    if (message == WM_COMMAND) {
        if (LOWORD(wparam) == IDC_PICK_LIST && HIWORD(wparam) == LBN_SELCHANGE) {
            chooser_show(window);
            return TRUE;
        }
        if (LOWORD(wparam) == IDC_PICK_LIST && HIWORD(wparam) == LBN_DBLCLK) {
            if (IsWindowEnabled(GetDlgItem(window, IDOK))) {
                PostMessageA(window, WM_COMMAND, IDOK, 0);
            }
            return TRUE;
        }
        if (LOWORD(wparam) == IDOK) {
            int sel = (int)SendDlgItemMessageA(window, IDC_PICK_LIST, LB_GETCURSEL, 0, 0);
            int index;
            if (sel < 0) {
                return TRUE;
            }
            index = (int)SendDlgItemMessageA(window, IDC_PICK_LIST, LB_GETITEMDATA, (WPARAM)sel, 0);
            if (!chooser.possible[index]) {
                return TRUE;
            }
            chooser.chosen = index;
            EndDialog(window, IDOK);
            return TRUE;
        }
        if (LOWORD(wparam) == IDCANCEL) {
            EndDialog(window, IDCANCEL);
            return TRUE;
        }
    } else if (message == WM_CLOSE) {
        EndDialog(window, IDCANCEL);
        return TRUE;
    }
    return FALSE;
}

/* Arms `event` for `game`: makes the island event due and remembers the
   pick.  1 on success. */
static int arm_pick(int game, const story_event *event) {
    if (!GAMES[game].arm()) {
        return 0;
    }
    pick_slot = event->slot;
    pick_game = game;
    pick_tick = STORY_TICK();
    pick_event = event;
    return 1;
}

/* The Pick Island Event upgrade, called by the Origins companion when its
   Pick Island Event button is clicked (the companion has already refused a
   click while the Island Event row is locked).  Shows the chooser, confirms
   the 0-point purchase, and arms the pick.  Returns 1 when an event is on
   its way, 0 otherwise. */
__declspec(dllexport) int __stdcall VvfpStoryPickIslandEvent(int game, HWND owner) {
    const story_game *g;
    const story_event *event;
    char label[160];
    char message[512];
    int i;
    if (!VvfpStoryActive(game)) {
        return 0;
    }
    g = &GAMES[game];
    drop_lapsed_pick();
    if (pick_slot >= 0 || g->island_pending()) {
        /* New Believers' Island Event and Barrel of Babies share one queue
           (either blocks both purchases); the pick shares it too. */
        MessageBoxA(owner,
                    game == 5
                        ? "An island event or a barrel of babies is already queued "
                          "and on its way.\n\nIt arrives shortly. Close this screen "
                          "and wait for it to arrive."
                        : "An island event is already queued and on its way.\n\n"
                          "It arrives shortly. Close this screen and wait for it to arrive.",
                    "Not right now", MB_OK | MB_ICONINFORMATION | MB_TOPMOST | MB_SETFOREGROUND);
        return 0;
    }
    if (last_failed_event != NULL) {
        label_of(last_failed_event, label, sizeof label);
        if (last_failed_lapsed) {
            wsprintfA(message,
                      "The last island event you picked, %s, did not happen within "
                      "ten minutes, so it was cancelled.", label);
        } else {
            wsprintfA(message,
                      "The last island event you picked, %s, could not happen when it "
                      "was due (it needs %s), so the island event the game chose "
                      "happened instead.",
                      label, last_failed_event->requires);
        }
        MessageBoxA(owner, message, "Pick Island Event",
                    MB_OK | MB_ICONINFORMATION | MB_TOPMOST | MB_SETFOREGROUND);
        last_failed_event = NULL;
    }
    chooser.game = g;
    chooser.chosen = -1;
    for (i = 0; i < g->event_count && i < STORY_MAX_EVENTS; ++i) {
        chooser.possible[i] = g->possible(&g->events[i]);
    }
    if (DialogBoxParamA(module_instance, MAKEINTRESOURCEA(IDD_PICK), owner, chooser_dialog, 0)
            != IDOK
        || chooser.chosen < 0) {
        return 0;
    }
    event = &g->events[chooser.chosen];
    label_of(event, label, sizeof label);
    wsprintfA(message,
              "Do you want to buy Pick Island Event (%s) for 0 tech points?\r\n"
              "Press OK to confirm, or Cancel.", label);
    if (MessageBoxA(owner, message, "Origins Upgrades",
                    MB_OKCANCEL | MB_ICONQUESTION | MB_TOPMOST | MB_SETFOREGROUND) != IDOK) {
        return 0;
    }
    /* The village may have moved on while the boxes were open. */
    if (g->island_pending() || !g->possible(event) || !arm_pick(game, event)) {
        MessageBoxA(owner, "That island event can not happen right now. No tech points have been deducted.",
                    "Origins Upgrades", MB_OK | MB_ICONINFORMATION | MB_TOPMOST | MB_SETFOREGROUND);
        return 0;
    }
    wsprintfA(message, "%s is on its way.", label);
    MessageBoxA(owner, message, "Origins Upgrades",
                MB_OK | MB_ICONINFORMATION | MB_TOPMOST | MB_SETFOREGROUND);
    return 1;
}

/* Whether a pick is armed and not yet delivered (the Origins companion uses
   it to explain the locked Island Event row). */
__declspec(dllexport) int __stdcall VvfpStoryPickPending(int game) {
    drop_lapsed_pick();
    return pick_slot >= 0 && pick_game == game;
}

BOOL WINAPI DllMain(HINSTANCE instance, DWORD reason, LPVOID reserved) {
    (void)reserved;
    if (reason == DLL_PROCESS_ATTACH) {
        module_instance = instance;
        DisableThreadLibraryCalls(instance);
    }
    return TRUE;
}

#ifdef VVFP_TEST
/* ---- Test build only ------------------------------------------------------- */

/* Site `index` of `game`: its address, the bytes verified there and the bytes
   written.  Returns the length, or 0 past the end.  Detours follow the
   writes; their written bytes are computed for this load of the DLL. */
__declspec(dllexport) int __stdcall VvfpStoryProbeSite(int game, int index, unsigned int *va,
                                                        unsigned char *expect,
                                                        unsigned char *replace) {
    const story_game *g;
    if (game < 1 || game > 5) {
        return 0;
    }
    g = &GAMES[game];
    if (index < g->write_count) {
        *va = g->writes[index].va;
        memcpy(expect, g->writes[index].expect, (size_t)g->writes[index].length);
        memcpy(replace, g->writes[index].replace, (size_t)g->writes[index].length);
        return g->writes[index].length;
    }
    index -= g->write_count;
    if (index < g->detour_count) {
        *va = g->detours[index].va;
        memcpy(expect, g->detours[index].expect, (size_t)g->detours[index].length);
        detour_bytes(&g->detours[index], replace);
        return g->detours[index].length;
    }
    return 0;
}

/* Arms a pick by its position in this game's event table without any
   dialog, at test tick `tick`.  Returns the game's index of the event. */
__declspec(dllexport) int __stdcall VvfpStoryProbeArm(int game, int position, DWORD tick) {
    const story_game *g;
    if (game < 1 || game > 5) {
        return -1;
    }
    g = &GAMES[game];
    if (position < 0 || position >= g->event_count) {
        return -1;
    }
    test_tick = tick;
    install_state[game] = 1;
    if (!arm_pick(game, &g->events[position])) {
        return -1;
    }
    return g->events[position].slot;
}

/* Arms a pick WITHOUT making the island event due (the delivery tests drive
   the selector directly). */
__declspec(dllexport) int __stdcall VvfpStoryProbeSetPick(int game, int position, DWORD tick) {
    const story_game *g;
    if (game < 1 || game > 5) {
        return -1;
    }
    g = &GAMES[game];
    if (position < 0 || position >= g->event_count) {
        return -1;
    }
    pick_slot = g->events[position].slot;
    pick_game = game;
    pick_tick = tick;
    pick_event = &g->events[position];
    return pick_slot;
}

__declspec(dllexport) void __stdcall VvfpStoryProbeSetTick(DWORD tick) {
    test_tick = tick;
}

__declspec(dllexport) int __stdcall VvfpStoryProbePending(int game) {
    return GAMES[game].island_pending();
}

__declspec(dllexport) int __stdcall VvfpStoryProbePossible(int game, int position) {
    return GAMES[game].possible(&GAMES[game].events[position]);
}

__declspec(dllexport) int __stdcall VvfpStoryProbeArmedSlot(void) {
    return pick_slot;
}
#endif
