"""Write docs/story-island-outcomes.md: every Pick Island Event setting, per game and event.

Generated from scripts/story_island_outcomes.py (and the per-game tables it
gathers), so the document always lists exactly what the companion offers.

    python scripts/build_story_outcomes_doc.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import story_island_events  # noqa: E402
import story_island_outcomes as data  # noqa: E402
from story_outcome_tables import plain  # noqa: E402

OUT = ROOT / "docs" / "story-island-outcomes.md"
NAMES = {"vv1": "A New Home", "vv2": "The Lost Children", "vv3": "The Secret City",
         "vv4": "The Tree of Life", "vv5": "New Believers"}
KIND = {"enum": "result", "amount": "amount", "loop": "each villager", "victim": "which villager"}


def _event_label(e: dict) -> str:
    return f"{e['title'].rstrip()} ({e['variant']})" if e["variant"] else e["title"]


def _control_line(c: dict) -> str:
    label = plain(c["label"]) or c["label"]
    if c["kind"] == "enum":
        values = "; ".join(plain(o["label"]) or o["label"] for o in c["options"])
    elif c["kind"] == "amount":
        lo, hi = c["base"], c["base"] + c["step"] * (c["bound"] - 1)
        unit = plain(c.get("unit")) or ""
        values = f"any of {min(lo, hi)} to {max(lo, hi)} {unit}".rstrip()
    elif c["kind"] == "loop":
        choices = [x for x, v in (("nobody", c["nobody"]), ("everyone", c["everyone"])) if v is not None]
        if c.get("record") is not None and len(choices) == 2:
            choices.append("the villagers chosen")
        values = ", ".join(choices)
        if c.get("warn_everyone"):
            values += " (everyone: a warning first)"
    else:
        values = "a villager the game itself could pick"
    return f"| {label} | {KIND[c['kind']]} | {values} |"


def counts(game: str) -> dict:
    cs = [c for v in data.CONTROLS[game].values() for c in v]
    return {
        "events": len(data.CONTROLS[game]),
        "settings": len(cs),
        "results": sum(len(c["options"]) for c in cs if c["kind"] == "enum"),
        "amounts": sum(c["kind"] == "amount" for c in cs),
        "loops": sum(c["kind"] == "loop" for c in cs),
        "victims": sum(c["kind"] == "victim" for c in cs),
        "strength": len(data.STRENGTH.get(game, {})),
        "unlocked": len([s for s in data.UNLOCKED.get(game, {}) if s not in data.DEAD_NOTES.get(game, {})]),
        "dead": len(data.DEAD_NOTES.get(game, {})),
    }


def build() -> str:
    lines = [
        "# Pick Island Event: every setting",
        "",
        "GENERATED by `scripts/build_story_outcomes_doc.py` from `scripts/story_island_outcomes.py`;",
        "do not edit. The evidence for each setting (the game's own code it was traced in) is in",
        "`scripts/story_outcomes_vv1.py` ... `story_outcomes_vv5.py` and `story_outcomes_gong.py`;",
        "how they work is in `docs/story-cheat-upgrades.md`.",
        "",
        "Every setting starts at **Random (original game)**. \"Result\" settings pick one of the",
        "event's own results (for a two-choice event, labelled with the choice they belong to);",
        "\"amount\" settings any value the game itself can roll; \"each villager\" settings who a roll",
        "the game makes for every villager hits; \"which villager\" settings the villager the event",
        "is about (one the game would not pick leaves the choice to the game).",
        "",
        "| Game | Events with settings | Settings | Result options | Amounts | Each-villager | Which-villager | Strength | Unlocked | Dead offered |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for game in NAMES:
        k = counts(game)
        lines.append(f"| {NAMES[game]} | {k['events']} | {k['settings']} | {k['results']} | {k['amounts']} | "
                     f"{k['loops']} | {k['victims']} | {k['strength']} | {k['unlocked']} | {k['dead']} |")
    lines.append("")
    for game in NAMES:
        lines += [f"## {NAMES[game]}", ""]
        for e in story_island_events.EVENTS[game]:
            slot = e["slot"]
            cs = data.CONTROLS[game].get(slot, [])
            strength = data.STRENGTH.get(game, {}).get(slot)
            notes = []
            if slot in data.DEAD_NOTES.get(game, {}):
                notes.append("never happens in the original game; offered because it works")
            elif slot in data.UNLOCKED.get(game, {}):
                notes.append("can be picked when its own timing/story condition does not hold")
            if not cs and not strength and not notes:
                continue
            title = _event_label(e) + (f" -- {'; '.join(notes)}" if notes else "")
            lines += [f"### {title}", ""]
            if cs or strength:
                lines += ["| Setting | Kind | Choices besides Random |", "| --- | --- | --- |"]
                lines += [_control_line(c) for c in cs]
                if strength:
                    lines.append("| Strength | strength | " + (
                        "1 to 10" if strength == "linear" else "1-4 (one baby), 5-7 (two), 8-10 (three)") + " |")
                lines.append("")
        omitted = data.OMITTED.get(game, {})
        if omitted:
            lines += [f"### Looked at and not offered ({NAMES[game]})", ""]
            for slot, items in omitted.items():
                for item in items if isinstance(items, list) else [items]:
                    text = plain(str(item)) or str(item)
                    lines.append(f"* {slot}: {text}")
            lines.append("")
    lines += ["## The Lost Children: Pick Gong of Wonder Outcome", "",
              "| Setting | Kind | Choices besides Random |", "| --- | --- | --- |"]
    lines += [_control_line(c) for c in data.GONG_CONTROLS["vv2"]]
    lines.append("")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    OUT.write_text(build(), encoding="utf-8", newline="\n")
    print(OUT)
