"""Compile native/shared/mask_identity.c into a 64-bit DLL for the test suite.

The safeguard ships inside 32-bit game companion DLLs, which cannot be called
from this 64-bit Python.  Because mask_identity.c is address-free -- it names no
game address and no record offset, taking all of that in a caller-supplied
adapter -- the very same source compiles for x64 and can be driven directly by
ctypes.  The tests therefore exercise the SHIPPED implementation rather than a
Python re-description of it.

Nothing is written into the repository: the caller supplies an output directory
(the tests use a temporary one).

Linking deliberately avoids the C runtime.  The module is freestanding by
design, so /NODEFAULTLIB /NOENTRY keeps the build independent of whichever
Windows SDK happens to be installed.  A tiny memset/memcpy shim is generated
into the output directory to satisfy any call the optimiser synthesises.
"""
from __future__ import annotations

import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "native" / "shared" / "mask_identity.c"
HEADER = ROOT / "native" / "shared" / "mask_identity.h"

EXPORTS = (
    "vv_identity_snapshot_build",
    "vv_identity_snapshot_is_stale",
    "vv_identity_preflight",
    "vv_identity_is_candidate",
)

# The optimiser may turn a zeroing loop into a memset call even though the
# source never names one.  Providing them keeps /NODEFAULTLIB viable.
_SHIM = """/* Generated by scripts/build_mask_identity_harness.py -- not part of the patch. */
#pragma function(memset, memcpy)   /* MSVC treats both as intrinsics otherwise */

void *memset(void *dst, int value, unsigned long long count)
{
    unsigned char *p = (unsigned char *)dst;
    while (count--) { *p++ = (unsigned char)value; }
    return dst;
}

void *memcpy(void *dst, const void *src, unsigned long long count)
{
    unsigned char *d = (unsigned char *)dst;
    const unsigned char *s = (const unsigned char *)src;
    while (count--) { *d++ = *s++; }
    return dst;
}
"""


class ToolchainMissing(RuntimeError):
    """No usable x64 MSVC toolchain was found on this machine."""


def _candidate_roots() -> list[Path]:
    roots: list[Path] = []
    for env in ("ProgramFiles", "ProgramFiles(x86)"):
        base = os.environ.get(env)
        if base:
            roots.append(Path(base) / "Microsoft Visual Studio")
    return [r for r in roots if r.is_dir()]


def find_toolchain() -> tuple[Path, Path]:
    """Return (cl.exe, link.exe) for the newest x64-hosted, x64-targeting MSVC."""
    found: list[tuple[tuple[int, ...], Path]] = []
    for root in _candidate_roots():
        for cl in root.glob("*/*/VC/Tools/MSVC/*/bin/Hostx64/x64/cl.exe"):
            version = cl.parents[3].name
            try:
                key = tuple(int(part) for part in version.split("."))
            except ValueError:
                key = (0,)
            found.append((key, cl))
    if not found:
        raise ToolchainMissing(
            "no Hostx64/x64 cl.exe found under any Visual Studio installation"
        )
    found.sort()
    cl = found[-1][1]
    link = cl.with_name("link.exe")
    if not link.is_file():
        raise ToolchainMissing(f"found {cl} but no link.exe beside it")
    return cl, link


def build(out_dir: Path) -> Path:
    """Compile the safeguard into `out_dir` and return the resulting DLL path."""
    if not SOURCE.is_file():
        raise FileNotFoundError(SOURCE)

    cl, link = find_toolchain()
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    shim = out_dir / "harness_shim.c"
    shim.write_text(_SHIM, encoding="ascii")

    dll = out_dir / "mask_identity_x64.dll"
    objs = []
    for src in (SOURCE, shim):
        obj = out_dir / (src.stem + ".obj")
        subprocess.run(
            [
                str(cl),
                "/nologo",
                "/c",
                "/O2",
                "/GS-",          # no security cookie: there is no CRT to supply it
                "/Gs1000000",    # no stack-probe calls
                f"/I{HEADER.parent}",
                f"/Fo{obj}",
                str(src),
            ],
            check=True,
            capture_output=True,
            cwd=out_dir,
        )
        objs.append(obj)

    subprocess.run(
        [
            str(link),
            "/nologo",
            "/DLL",
            "/NOENTRY",
            "/NODEFAULTLIB",
            f"/OUT:{dll}",
            *[f"/EXPORT:{name}" for name in EXPORTS],
            *[str(o) for o in objs],
        ],
        check=True,
        capture_output=True,
        cwd=out_dir,
    )
    return dll


if __name__ == "__main__":
    import sys
    import tempfile

    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(tempfile.mkdtemp())
    print(build(target))
