"""Bucket the VV1 head variants by hair colour for the "Village-wide Heads"
override in Change Appearance for All.

Each head preview bitmap (native/vv1_origins_icons/appearance/head_{m,f}.bmp) is
40x1300 = twenty 40x65 variant cells. For each variant we sample the hair band
(the top of the head), drop the flat background and the villager's skin tone,
take the dominant remaining colour, and classify it into one of five buckets:

    0 Black   1 Brown   2 Red/Ginger   3 Blonde   4 Other (gray/white/dyed/bald)

The result is written as native/vv1_origins_icons/vv1_head_buckets.h, which the
DLL includes; "All <colour> Hair" then picks a random index from that gender's
bucket. Heuristic, but the buckets only need to look right, and Other is the
catch-all. Run with --check to verify the committed header is up to date.
"""
from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
APPEARANCE = ROOT / "native" / "vv1_origins_icons" / "appearance"
HEADER = ROOT / "native" / "vv1_origins_icons" / "vv1_head_buckets.h"

CELL_W, CELL_H = 40, 65
HAIR_BAND_H = 24          # top strip of the cell that holds the hair
BG = (236, 236, 236)      # flat preview background
COLOUR_NAMES = ["Black", "Brown", "Red/Ginger", "Blonde", "Other"]
BLACK, BROWN, RED, BLONDE, OTHER = range(5)


def _is_bg(p):
    return abs(p[0] - BG[0]) < 12 and abs(p[1] - BG[1]) < 12 and abs(p[2] - BG[2]) < 12


def _is_skin(r, g, b):
    """VV villager skin is a light warm tan: bright, r>g>b, moderate spread."""
    return r > 165 and g > 120 and b > 90 and r >= g >= b and 25 < (r - b) < 135


def _dominant_hair(cell):
    """Most common non-bg, non-skin colour in the hair band (quantised)."""
    band = cell.crop((0, 0, CELL_W, HAIR_BAND_H))
    counts = Counter()
    for (r, g, b) in band.getdata():
        if _is_bg((r, g, b)) or _is_skin(r, g, b):
            continue
        counts[(r // 16 * 16, g // 16 * 16, b // 16 * 16)] += 1
    if not counts:
        return None
    return counts.most_common(1)[0][0]


def _classify(rgb):
    if rgb is None:
        return OTHER            # essentially no hair sampled -> bald/other
    r, g, b = rgb
    mx = max(r, g, b)
    if mx < 64:
        return BLACK
    # near-grey (white / grey / silver / dyed-flat) -> Other, before the warm
    # buckets, so a light grey isn't mistaken for brown.
    if mx - min(r, g, b) < 40:
        return OTHER
    # blonde: light and yellow -- high red+green, distinctly lower blue
    if r >= 176 and g >= 144 and b < g - 24:
        return BLONDE
    # red / ginger: strongly red-orange, red clearly dominates green
    if r >= 112 and g < 168 and r > 2 * g - 24 and b < g + 24:
        return RED
    # brown: warm r>=g>=b, mid tone
    if r >= g >= b and r >= 64:
        return BROWN
    return OTHER               # near-grey / off-spectrum / dyed


# Valid head-variant domain per sex, mirroring the DLL's VV_HEAD_COUNT_M/F and
# the per-sex Head cyclers (which run 0..18 for males, 0..19 for females). The
# male sheet has a 20th cell (index 19) that the game reserves for the special
# status-199 appearance -- it is NOT a normal male head, so it must never be
# handed out by "All <colour> Hair". Bucket only the valid domain.
HEAD_COUNT_M = 19  # males: indices 0..18 (19 is the reserved status-199 head)
HEAD_COUNT_F = 20  # females: indices 0..19 all valid


def _bucket_file(path, max_variants=None):
    im = Image.open(path).convert("RGB")
    variants = im.height // CELL_H
    if max_variants is not None:
        variants = min(variants, max_variants)
    buckets = [[] for _ in range(5)]
    detail = []
    for v in range(variants):
        cell = im.crop((0, v * CELL_H, CELL_W, (v + 1) * CELL_H))
        dom = _dominant_hair(cell)
        c = _classify(dom)
        buckets[c].append(v)
        detail.append((v, dom, COLOUR_NAMES[c]))
    return buckets, detail


def build_header() -> str:
    male, _ = _bucket_file(APPEARANCE / "head_m.bmp", HEAD_COUNT_M)
    female, _ = _bucket_file(APPEARANCE / "head_f.bmp", HEAD_COUNT_F)

    def arr(name, buckets):
        rows = []
        for c in range(5):
            vals = ", ".join(str(v) for v in buckets[c]) or "0"
            rows.append(f"    {{ {vals} }},")
        return f"static const unsigned char {name}[VV_HAIR_COLOURS][20] = {{\n" + "\n".join(rows) + "\n};"

    def counts(name, buckets):
        vals = ", ".join(str(len(buckets[c])) for c in range(5))
        return f"static const int {name}[VV_HAIR_COLOURS] = {{ {vals} }};"

    lines = [
        "/* Head-index buckets by hair colour, per gender -- GENERATED by",
        " * scripts/build_vv1_head_hair_buckets.py. Do not edit by hand.",
        " *",
        " * Colour index: 0=Black, 1=Brown, 2=Red/Ginger, 3=Blonde, 4=Other.",
        " * vv1_head_pick(sex, colour, rng) returns a random head index from that",
        " * gender+colour bucket, or -1 if empty. sex: 1=male, 0=female.",
        " */",
        "#ifndef VV1_HEAD_BUCKETS_H",
        "#define VV1_HEAD_BUCKETS_H",
        "",
        "#define VV_HAIR_COLOURS 5",
        "",
        arr("vv1_head_bucket_m", male),
        arr("vv1_head_bucket_f", female),
        counts("vv1_head_bucket_m_count", male),
        counts("vv1_head_bucket_f_count", female),
        "",
        "static int vv1_head_pick(int sex, int colour, unsigned int *rng) {",
        "    const unsigned char *bucket;",
        "    int n;",
        "    if (colour < 0 || colour >= VV_HAIR_COLOURS) {",
        "        return -1;",
        "    }",
        "    if (sex) {",
        "        bucket = vv1_head_bucket_m[colour];",
        "        n = vv1_head_bucket_m_count[colour];",
        "    } else {",
        "        bucket = vv1_head_bucket_f[colour];",
        "        n = vv1_head_bucket_f_count[colour];",
        "    }",
        "    if (n <= 0) {",
        "        return -1;",
        "    }",
        "    *rng = *rng * 1664525u + 1013904223u;",
        "    return (int)bucket[(*rng >> 16) % (unsigned int)n];",
        "}",
        "",
        "#endif /* VV1_HEAD_BUCKETS_H */",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify committed header")
    ap.add_argument("--show", action="store_true", help="print per-variant classification")
    args = ap.parse_args()
    if args.show:
        for label, f in (("male", "head_m.bmp"), ("female", "head_f.bmp")):
            _, detail = _bucket_file(APPEARANCE / f)
            print(f"== {label} ==")
            for v, dom, name in detail:
                print(f"  var {v:2d}: dom={dom} -> {name}")
    header = build_header()
    if args.check:
        if not HEADER.exists() or HEADER.read_text(encoding="utf-8") != header:
            print("vv1_head_buckets.h is stale; re-run build_vv1_head_hair_buckets.py")
            return 1
        print("vv1_head_buckets.h is up to date")
        return 0
    HEADER.write_text(header, encoding="utf-8")
    print(f"wrote {HEADER}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
