"""The island events "Pick Island Event" offers, per game, and the ones it does not.

Read from each game's own executable (see docs/story-cheat-upgrades.md for the
evidence): every entry is an event the game's own island-event scheduler can
run, under the official English title that game's own string data gives it.
`slot` is the value the game's own chooser produces for that event:

* A New Home and The Lost Children choose a family first, then an event in
  it, so their slot is (family << 6) | index.
* The Secret City, The Tree of Life and New Believers keep one table of event
  objects; their slot is the index in that table.

`variant` tells apart events that share a title (it is shown after the title
in the chooser); for an event whose picked villager is always one sex it
names that sex (the owner, 2026-10-01: "Female" / "Male", read from each
event's own picker -- the sex it passes -- and its text).  `requires` is
what the event's own condition needs, shown when the condition does not
hold.  Developer-dead events are listed in
EXCLUDED with the reason; they are never offered.
"""
from __future__ import annotations

ALWAYS = "nothing beyond an island event being possible"
# A developer-dead event proven to work: its own condition never holds.
NEVER = "nothing it can have: the original game never runs it (picking it makes it happen)"

# An event that exists only with The Lost Children's Restore Missing Island
# Events row ticked.
RESTORE = "the Restore Missing Island Events patch, which adds this event"

# A New Home families (story_vv1.inc).
VV1_ISLAND, VV1_ENCOUNTER, VV1_CRATE = 0, 1, 2
# The Lost Children families (story_vv2.inc).
VV2_C, VV2_A, VV2_B = 0, 1, 2


def _slot(family: int, index: int) -> int:
    return (family << 6) | index


def _e(slot, title, description, *, variant="", requires=ALWAYS):
    return {
        "slot": slot,
        "title": title,
        "variant": variant,
        "description": description,
        "requires": requires,
    }


EVENTS: dict[str, list[dict]] = {
    "vv1": [
        # The island events of 0x427CA0 (case, magnitude clamp(population/3, 1, 10)).
        _e(_slot(VV1_ISLAND, 0), "The Bad Little Monkey",
           "A monkey ransacks the research table: the tribe loses tech points."),
        _e(_slot(VV1_ISLAND, 1), "A Mighty Storm",
           "A typhoon strikes in the night and washes away all of the stored food.",
           requires=NEVER),
        _e(_slot(VV1_ISLAND, 2), "The Plague of Parrots",
           "A flock of wild parrots eats many of the berries."),
        _e(_slot(VV1_ISLAND, 3), "A Plague of Locusts",
           "Locusts devour the crops in the field.",
           requires="crops growing in the farm field"),
        _e(_slot(VV1_ISLAND, 4), "The Measles Epidemic",
           "Every child in the village falls ill with measles.",
           requires="at least one living child"),
        _e(_slot(VV1_ISLAND, 5), "The South Wind",
           "A hot wind withers the berries, scorches the crops and spoils some stored food."),
        _e(_slot(VV1_ISLAND, 6), "The Heat Wave",
           "A heat wave: the villagers stop working to seek relief until it passes."),
        _e(_slot(VV1_ISLAND, 7), "Isola Day Celebration",
           "The villagers celebrate their arrival on Isola with a feast (uses some food)."),
        _e(_slot(VV1_ISLAND, 8), "Blessings Day Celebration",
           "The villagers give thanks with dancing, ceremonies and a feast (uses some food)."),
        _e(_slot(VV1_ISLAND, 9), "The Big Wave",
           "A giant wave covers the cleaned-up beach with debris again.",
           requires="the beach to have been cleaned up completely"),
        _e(_slot(VV1_ISLAND, 10), "The Good Little Monkey",
           "A monkey stumbles on useful discoveries at the research table: the tribe gains tech points."),
        _e(_slot(VV1_ISLAND, 11), "The Greedy Little Monkey",
           "Chasing a food thief, the villagers find a cache of bananas: the tribe gains food."),
        _e(_slot(VV1_ISLAND, 12), "The Barrel O` Babies",
           "A barrel of babies washes up and they join the village (more of them in a bigger village).",
           requires="room in the village for new villagers"),
        _e(_slot(VV1_ISLAND, 13), "The North Wind",
           "A cool, moist wind refreshes the crops and the berry bush."),
        _e(_slot(VV1_ISLAND, 14), "The Helpful Honeybees",
           "Honeybees pollinate the berry bush and it thrives."),
        # The villager encounters (0x41A460): two-choice events.
        _e(_slot(VV1_ENCOUNTER, 0), "The Trapped Whale",
           "A villager finds a stranded whale: free it, or harvest it for food.",
           requires="the tribe's spirituality below its highest level (freeing the whale raises it)"),
        _e(_slot(VV1_ENCOUNTER, 1), "The Strange Berries",
           "A villager finds strange berries: taste them (risky) or leave them."),
        _e(_slot(VV1_ENCOUNTER, 2), "The Old Drum",
           "A villager finds a heavy old drum: cut it open, or keep it."),
        _e(_slot(VV1_ENCOUNTER, 3), "The Mysterious Face",
           "A villager sees a face in the trees: take a closer look (risky), or back away."),
        _e(_slot(VV1_ENCOUNTER, 4), "The Visitor",
           "A stranger in a boat asks for plants and seeds: help him, or refuse.",
           requires="the tribe's medicine below its highest level (the visitor raises it)"),
        _e(_slot(VV1_ENCOUNTER, 5), "The Furry Food",
           "The stored food goes moldy: remove the moldy pieces (some villagers get stomach "
           "trouble), or throw out all the food.",
           requires=NEVER),
        _e(_slot(VV1_ENCOUNTER, 6), "A Mysterious Vial",
           "A villager finds a vial of oily red liquid: drink it (risky), or pour it out.",
           variant="red liquid"),
        _e(_slot(VV1_ENCOUNTER, 7), "The Troubled Child",
           "An unusually bright child needs direction: farming, or research.",
           requires="at least one living child"),
        _e(_slot(VV1_ENCOUNTER, 8), "A Mysterious Vial",
           "A villager finds a vial of oily blue liquid: drink it, or pour it out.",
           variant="blue liquid"),
        _e(_slot(VV1_ENCOUNTER, 9), "The Suspicious Monkey",
           "A monkey hangs around the food bin: chase it away, or wait and see.",
           requires="at least one living child"),
        _e(_slot(VV1_ENCOUNTER, 10), "The Wild Mushroom",
           "A villager picks a mushroom the monkeys eat: taste it (risky), or discard it."),
        _e(_slot(VV1_ENCOUNTER, 11), "The Black Pearl",
           "A villager finds a stunning black pearl: share it, or keep it."),
        _e(_slot(VV1_ENCOUNTER, 12), "The Dream",
           "A villager dreams of two caves: enter the right cave, or the left."),
        _e(_slot(VV1_ENCOUNTER, 13), "The Moth",
           "A villager finds a moth struggling out of its cocoon: help it, or leave it."),
        _e(_slot(VV1_ENCOUNTER, 14), "The Book",
           "A villager finds a book, The Island of Pearls: read it, or give it to the researchers."),
        _e(_slot(VV1_ENCOUNTER, 15), "The Brass Compass",
           "A villager finds a brass compass: use it to mash berries, or give it to the researchers."),
        # The Mysterious Crate / Vial (0x42D0E0): open it or leave it.
        _e(_slot(VV1_CRATE, 0), "A Mysterious Crate",
           "A wooden crate washes up: opening it gives food.", variant="wooden"),
        _e(_slot(VV1_CRATE, 1), "A Mysterious Crate",
           "A carefully sealed crate washes up: opening it gives tech points.",
           variant="carefully sealed"),
        _e(_slot(VV1_CRATE, 2), "A Mysterious Crate",
           "A badly weathered crate washes up: rusty tools give tech points, but villagers fall ill.",
           variant="badly weathered"),
        _e(_slot(VV1_CRATE, 3), "A Mysterious Crate",
           "A rotting crate washes up: angry rats bite and spread disease.",
           variant="rotting"),
        _e(_slot(VV1_CRATE, 4), "A Mysterious Crate",
           "A watertight crate washes up: babies inside join the village if there is room.",
           variant="watertight"),
        _e(_slot(VV1_CRATE, 5), "A Mysterious Crate",
           "An old fruit crate washes up: giant spiders badly injure the villager who opens it.",
           variant="old fruit"),
        _e(_slot(VV1_CRATE, 6), "A Mysterious Vial",
           "A vial washes up: drinking it changes the villager's appearance.",
           variant="red, from the sea"),
        _e(_slot(VV1_CRATE, 7), "A Mysterious Vial",
           "A vial washes up: drinking it raises one of the villager's skills.",
           variant="blue, from the sea"),
        _e(_slot(VV1_CRATE, 8), "A Mysterious Vial",
           "A vial washes up: drinking it lowers all of the villager's skills.",
           variant="fizzy, from the sea"),
    ],
    "vv2": [
        # Family C: the single-result events of 0x433600 (magnitude clamp(population/3, 1, 10)).
        _e(_slot(VV2_C, 0), "The Obnoxious Parrot",
           "A parrot keeps startling the researchers: the tribe loses tech points."),
        _e(_slot(VV2_C, 1), "The Flash Flood",
           "A flash flood soaks the food bin: only the top layer of food stays edible."),
        _e(_slot(VV2_C, 2), "The Dense Fog",
           "After a thick fog the food bin is missing food.", variant="food lost"),
        _e(_slot(VV2_C, 3), "The Dense Fog",
           "After a thick fog things are missing from the research table: tech points lost.",
           variant="tech lost"),
        _e(_slot(VV2_C, 5), "The East Wind",
           "A scorching east wind parches the island and slows the villagers' work."),
        _e(_slot(VV2_C, 6), "The Heat Wave",
           "A heat wave: the villagers stop working to seek relief until it passes."),
        _e(_slot(VV2_C, 7), "Isola Day Celebration",
           "The villagers celebrate their arrival on Isola with dancing and feasts."),
        _e(_slot(VV2_C, 8), "Day of Honor",
           "The villagers honor those who have passed.",
           requires="someone in the village to have died"),
        _e(_slot(VV2_C, 9), "Day of Elders",
           "The villagers celebrate the wise elders of the village."),
        _e(_slot(VV2_C, 10), "Blessings Day Celebration",
           "The villagers give thanks with dancing, ceremonies and a feast.", variant="first version"),
        _e(_slot(VV2_C, 11), "The Epidemic",
           "A disease spreads from a sick parrot through the village: every doctor is needed.",
           requires="the village's later technologies (the game's own advanced-village check)"),
        _e(_slot(VV2_C, 12), "Blessings Day Celebration",
           "The villagers give thanks with dancing, ceremonies and a feast.", variant="second version"),
        _e(_slot(VV2_C, 13), "The Spring Allergies",
           "Spring pollen gives most of the villagers allergies."),
        _e(_slot(VV2_C, 14), "Rats!",
           "Hundreds of rats swarm through the village, biting villagers and fouling it.",
           requires="the village's later technologies (the game's own advanced-village check)"),
        _e(_slot(VV2_C, 15), "Where Are The Infants?",
           "The village's infants are carried off during the night.",
           requires="a mother with an infant, and the village's later technologies"),
        _e(_slot(VV2_C, 16), "A Dangerous Mission",
           "Eight of the youngest, strongest adults sail off for the south shore and leave the village.",
           requires="a population of more than 60"),
        _e(_slot(VV2_C, 17), "The  Foul Passing",
           "Something foul passes through: crops, coconuts and the food bin are ruined.",
           requires="the village's later technologies (the game's own advanced-village check)"),
        _e(_slot(VV2_C, 18), "The Mosquito Swarm",
           "Mosquitoes swarm the island: some villagers fall ill and the adults take refuge in "
           "the water.", requires=NEVER),
        _e(_slot(VV2_C, 19), "The Friendly Parrot",
           "A friendly parrot drops nuts into the food bin: the tribe gains food."),
        _e(_slot(VV2_C, 20), "The Dragonfly Migration",
           "Dragonflies drive off the biting insects: every villager is restored to full health "
           "and cured of sickness.", requires=NEVER),
        _e(_slot(VV2_C, 21), "The Barrel O` Babies",
           "A barrel of babies washes up and they join the village (more of them in a bigger village).",
           requires="room in the village for new villagers"),
        _e(_slot(VV2_C, 22), "The West Wind",
           "A cool, moist wind refreshes the crops and coconut trees."),
        _e(_slot(VV2_C, 23), "The Dense Fog",
           "After a thick fog, useful formulae are found on the research table: tech points gained.",
           variant="tech gained"),
        _e(_slot(VV2_C, 24), "The Dense Fog",
           "After a thick fog, the food bin holds more food.", variant="food gained"),
        _e(_slot(VV2_C, 25), "Old Friends",
           "A couple from the south shore finds the village and joins it.",
           requires="room in the village for new villagers"),
        _e(_slot(VV2_C, 26), "Science Awareness Day",
           "The village celebrates its researchers with demonstrations and lectures; the children "
           "gain research skill.", requires=NEVER),
        _e(_slot(VV2_C, 27), "The Mother Parrot",
           "The children watch a mother parrot and learn about parenting."),
        # The lore pages of Restore Missing Island Events (its own row): one
        # body behind single-result case 4, rand(3) picks the page.  Their
        # slots, 28-30, are past the case roll: Pick Island Event delivers
        # one as case 4 and answers the page roll (story_vv2.inc).
        _e(_slot(VV2_C, 28), "The Tattered Diary",
           "A villager finds a half-rotten diary whose last page tells of a scout sent to watch "
           "the newcomers for magic.", requires=RESTORE),
        _e(_slot(VV2_C, 29), "The Doctrine of Magicians",
           "A villager finds a page praising the magic of Isola and the Magicians' artifacts.",
           requires=RESTORE),
        _e(_slot(VV2_C, 30), "The Doctrine of Naturalists",
           "A villager finds a page telling how the Naturalists banished the Magicians.",
           requires=RESTORE),
        # Family A: the two-choice events of 0x41F570.
        _e(_slot(VV2_A, 0), "The Ancient Gold Coin",
           "A villager finds a gold coin: wear it as an ornament, or give it to the scientists.",
           requires="the tribe's culture below the level the gold coin gives"),
        _e(_slot(VV2_A, 1), "The Cursed Idol",
           "A villager finds a cursed statuette: destroy it, or offer food to lift the curse.",
           requires="at least 250 food"),
        _e(_slot(VV2_A, 2), "The Prettiest Tribe Girl",
           "A young woman wants to be declared the prettiest in the tribe.",
           requires="at least one adult woman",
           variant="Female"),
        _e(_slot(VV2_A, 3), "The Strange Request",
           "Biggles wants to be left alone at the research table: allow it, or refuse."),
        _e(_slot(VV2_A, 4), "The Savage Child",
           "A wild boy is found at the research table: lure him in with food, or chase him away.",
           requires="room in the village for a new villager"),
        _e(_slot(VV2_A, 5), "The Voices In The Brush",
           "A villager hears voices in the brush: investigate (risky), or head back."),
        _e(_slot(VV2_A, 6), "For The Birds",
           "A child sees sea birds leaving fish on the rocks: taste the fish, or leave it.",
           requires="at least one living child"),
        _e(_slot(VV2_A, 7), "The Fastest Runner",
           "A villager brags about being the fastest: hold a race, or agree."),
        _e(_slot(VV2_A, 8), "The Nightmare",
           "A villager thrashes in a nightmare: wake them, or let them sleep."),
        _e(_slot(VV2_A, 9), "A Bump On The Head",
           "A villager falls from a tree and loses their memory: another bump, or rest."),
        _e(_slot(VV2_A, 10), "The Child Prodigy",
           "A gifted child builds amazing models: let them play, or apprentice them to the researchers.",
           requires="at least one living child"),
        _e(_slot(VV2_A, 11), "The Swarm Of Dragonflies",
           "Dragonflies gather at the pond: chase them away, or ignore them."),
        _e(_slot(VV2_A, 12), "The Black Seeds",
           "A villager finds strange black seeds: eat them, or plant them."),
        _e(_slot(VV2_A, 13), "The Crystal Ball",
           "A villager finds a strange ball: keep it, or give it to the children.",
           requires="at least one adult (with Fix Vanilla Bugs, also at least two living villagers)"),
        _e(_slot(VV2_A, 14), "The Silver Mirror",
           "A villager finds a silver mirror and must speak one of two words written on it.",
           requires="at least two villagers"),
        _e(_slot(VV2_A, 15), "The Huge Coconut",
           "A giant coconut falls: soften it in the pond, or hurl it from the diving rock."),
        _e(_slot(VV2_A, 16), "The Falling Star",
           "A villager sees a falling star: wish for themselves, or for the village."),
        _e(_slot(VV2_A, 17), "The Hole In The Sand",
           "A villager finds a strange hole on the beach: investigate it, or fill it in."),
        _e(_slot(VV2_A, 18), "The Spyglass",
           "A villager finds a spyglass: keep it, or give it to the scientists.",
           requires="the tribe's exploration below the level the spyglass gives"),
        _e(_slot(VV2_A, 19), "The Love Note",
           "A man finds a love note from a secret admirer: write a poem, or hide to catch the poet.",
           requires="at least one adult man and one adult woman",
           variant="Male"),
        _e(_slot(VV2_A, 20), "The White Pearl",
           "A villager finds a huge white pearl: keep it, or show it to the tribe."),
        # Family B: the Mysterious Sack / Vial of 0x437AC0 (open it or leave it).
        _e(_slot(VV2_B, 0), "A Mysterious Sack",
           "A thick plastic sack washes up: opening it gives food.", variant="thick plastic"),
        _e(_slot(VV2_B, 1), "A Mysterious Sack",
           "A carefully sealed sack washes up: opening it gives tech points.",
           variant="carefully sealed"),
        _e(_slot(VV2_B, 2), "A Mysterious Sack",
           "A somewhat compromised sack washes up: old tools give tech points, but villagers fall ill.",
           variant="somewhat compromised"),
        _e(_slot(VV2_B, 3), "A Mysterious Sack",
           "A thick canvas sack washes up: starving mice inside bite the villagers.",
           variant="thick canvas"),
        _e(_slot(VV2_B, 4), "A Mysterious Sack",
           "A stained burlap sack washes up: fire ants inside sting the villager who opens it.",
           variant="stained, heavy burlap"),
        _e(_slot(VV2_B, 5), "A Mysterious Vial",
           "A vial of green liquid: drinking it changes the villager's looks.", variant="green"),
        _e(_slot(VV2_B, 6), "A Mysterious Vial",
           "A vial of orange liquid: drinking it raises one of the villager's skills.", variant="orange"),
        _e(_slot(VV2_B, 7), "A Mysterious Vial",
           "A vial of fragrant liquid: drinking it lowers all of the villager's skills.",
           variant="fragrant"),
    ],
    "vv3": [
        _e(1, "The Tsunami",
           "A tsunami crashes into the village, destroying structures and sweeping villagers away.",
           requires="the game's own condition for the tsunami (two or more of the villagers it checks)"),
        _e(2, "The Plague Of Ants", "Ants infest the granary: some food is lost."),
        _e(3, "The Science Fair", "The children hold a science fair contest.",
           requires="at least three children"),
        _e(4, "The Allergy Season", "Many villagers suffer a bout of hay fever."),
        _e(5, "Isola Day Celebration", "The villagers celebrate their arrival on Isola with feasts."),
        _e(6, "Day of Honor", "The villagers pay their respects to those who have passed on.",
           requires="at least two graves"),
        _e(7, "The Canoe from the Other Side",
           "A villager from another part of Isola arrives by canoe and joins the village.",
           requires="room in the village for a new villager"),
        _e(8, "The Mysterious Fog", "After a fog, honeycombs appear: the village gains food.",
           variant="food gained"),
        _e(9, "The Mysterious Fog", "After a fog, some food has been stolen.", variant="food lost"),
        _e(10, "The Mysterious Fog", "After a fog, useful instruments appear: the village gains tech points.",
           variant="tech gained"),
        _e(11, "The Mysterious Fog", "After a fog, research tools have been stolen: tech points lost.",
           variant="tech lost"),
        _e(12, "Blessings Day Celebration", "The villagers give thanks with dancing, ceremonies and a feast."),
        _e(13, "The Miraculous Bloom", "Flowers bloom everywhere and the bees make a lot of honey.",
           requires="the game's own condition for the bloom"),
        _e(14, "The Reflection in the Water",
           "A villager sees a sad royal couple in a reflection (a story moment)."),
        _e(15, "The Daredevil", "A villager teases sharks: swim with them, or rethink the plan.",
           requires="a man the event can be about, and at least two women",
           variant="Male"),
        _e(16, "The Ghostly Dream", "A ghostly lady visits a dream: study nature, or the healing arts.",
           variant="nature or healing", requires="a villager the event can be about"),
        _e(17, "The Ghostly Dream", "A ghostly old man visits a dream: research, or architecture.",
           variant="research or architecture", requires="a villager the event can be about"),
        _e(18, "The Crystal of Reflections", "A villager finds an alluring crystal: keep it, or dispose of it.",
           requires="a villager the event can be about"),
        _e(19, "The Bitter Brown Beans", "A crate of roasted beans: taste them, or use them for dye.",
           variant="taste or dye", requires="a villager the event can be about"),
        _e(20, "The Bitter Brown Beans", "A crate of roasted beans: brew them, or use them as fertilizer.",
           variant="brew or fertilizer", requires="a villager the event can be about"),
        _e(21, "The Ancient Tablet", "An engraved tablet: use it for laundry, or for decoration.",
           variant="laundry or decoration", requires="a villager the event can be about"),
        _e(22, "The Ancient Tablet", "An engraved tablet: focus research on it, or put it on display.",
           variant="research or display", requires="a villager the event can be about"),
        _e(23, "The Low Tide", "A child finds fish stranded by the low tide: grab them, or move to high ground.",
           requires="a villager the event can be about, and at least eight villagers"),
        _e(24, "The Ants and the Granary", "A child sees ants at the granary: sweep them away, or let them be.",
           requires="a child the event can be about"),
        _e(25, "The Green Pearl", "A villager finds a green pearl: grind it into powder, or wear it.",
           requires="a villager the event can be about"),
        _e(26, "The Blue Pearl", "A villager finds a blue pearl: grind it into powder, or examine it.",
           requires="a villager the event can be about"),
        _e(27, "The Lazy Apprentice", "An apprentice wants a new master: stay, or find a new teacher.",
           requires="an apprentice the event can be about"),
        _e(28, "The Omen in the Clouds", "A villager sees an omen: warn the villagers, or perform a dance.",
           requires="a villager the event can be about"),
        _e(29, "The Playful Otters", "A child watches otters: throw them food, or keep watching.",
           requires="a child the event can be about"),
        _e(30, "The Ant Hill", "A child finds an ant hill: poke it, or drop bits of food.",
           requires="a child the event can be about"),
        _e(31, "The Red Starfish", "A villager finds a red starfish: pick it up, or leave it.",
           requires="a villager the event can be about"),
        _e(32, "The Blue Starfish", "A villager finds a blue starfish: pick it up, or leave it.",
           requires="a villager the event can be about"),
        _e(33, "Bed Bugs", "Something stings a villager in bed: swat it, or have a closer look.",
           requires="a villager the event can be about"),
        _e(34, "The Lovers", "A woman courts a man: a carved knife, or a shark-tooth necklace.",
           variant="Female", requires="a woman the event can be about"),
        _e(35, "The Lovers", "A man courts a woman: a shell necklace, or flowers.",
           variant="Male", requires="a man the event can be about"),
        _e(36, "The Medical Emergency",
           "A villager falls gravely ill: attempt an ancient procedure, or let the illness run its course.",
           requires="a villager the event can be about"),
        _e(37, "The Mysterious Vial", "A crystal vial on the beach: taste it, or bring it back.",
           variant="quartz", requires="a villager the event can be about"),
        _e(38, "The Mysterious Vial", "A crystal vial on the beach: taste it, or bring it back.",
           variant="obsidian", requires="a villager the event can be about"),
        _e(39, "The Mysterious Vial", "A crystal vial on the beach: taste it, or bring it back.",
           variant="amber", requires="a villager the event can be about"),
        _e(40, "The Mango and the Papaya", "A villager with a mango sees a papaya: swim for it, or keep the mango.",
           requires="a villager the event can be about"),
        _e(41, "The Mysterious Crate", "A crate washes up: open it, or shove it back out to sea.",
           requires="a villager the event can be about"),
        _e(42, "Vanity and the Bee", "A vain young woman and a bee: run to the water, or swat at it.",
           requires="a woman the event can be about",
           variant="Female"),
        _e(43, "The Noisy Bird", "A noisy bird disrupts research: scare it away, or leave it alone.",
           requires="a woman the event can be about",
           variant="Female"),
        _e(44, "The Hole in the Hut", "A draughty hole in a hut: patch it with beeswax, or tree sap.",
           requires="a villager the event can be about"),
        _e(45, "The Royal Jelly", "A villager tries royal jelly: a clear vial, or a dark vial.",
           requires="a villager the event can be about"),
        _e(46, "The Shooting Star", "A child sees a shooting star: tell the others, or stay and watch.",
           requires="a child the event can be about"),
        _e(47, "The Chief's Address", "The tribal chief gives the State of the Village address.",
           requires="a tribal chief"),
        _e(48, "The Rainy Season", "The rainy season begins with a heavy afternoon monsoon."),
        _e(49, "The Cold Snap", "An unseasonable cold sends the villagers to huddle by the fire.",
           requires="the game's own condition for the cold snap"),
        _e(50, "The Salty Air", "A salty wind forces the villagers to hide until it settles."),
        _e(51, "The Oppressive Humidity", "Hot, humid weather: the villagers can barely work."),
        _e(52, '"Thick as Pea Soup"', "A thick fog makes it hard to get the chores done."),
        _e(53, "The Stinging Jellyfish", "A jellyfish invasion stings many villagers."),
        _e(54, "The Mushroom Celebration", "The children are celebrated for collecting their 500th mushroom.",
           requires="500 mushrooms collected"),
        _e(55, "The Yellow Geckos", "Lucky yellow geckos clear the huts of bugs."),
        _e(56, "The Return of Biggles", "A mysterious figure works in the lab at night: confront him, or watch.",
           requires="a villager the event can be about"),
        _e(57, "Another One of Those Barrels ", "A barrel of babies washes up and they join the village.",
           requires="room in the village for new villagers"),
    ],
    "vv4": [
        _e(2, "The Creeping Mold", "A toxic mold spreads in the food bin: some food is ruined."),
        _e(3, "The Allergy Season", "Many villagers suffer a bout of hay fever."),
        _e(4, "Isola Day Celebration", "The villagers celebrate their arrival on Isola with feasts."),
        _e(5, "Day of Honor", "The villagers pay their respects to those who have passed on.",
           requires="the game's own condition for the day of honor (graves)"),
        _e(6, "The Canoe from the Other Side",
           "A canoe lands on the beach and a villager from another part of Isola joins the village.",
           requires=NEVER + "; it needs room in the village for a new villager"),
        _e(7, "The Mysterious Footprints", "Footprints appear overnight, and honeycombs: the village gains food.",
           variant="food gained"),
        _e(8, "The Mysterious Footprints", "Footprints appear overnight, and food is stolen.",
           variant="food lost"),
        _e(9, "The Mysterious Footprints", "Footprints appear overnight, and useful instruments: tech points gained.",
           variant="tech gained"),
        _e(10, "The Mysterious Footprints", "Footprints appear overnight, and research tools are stolen.",
           variant="tech lost"),
        _e(11, "Blessings Day Celebration", "The villagers give thanks with dancing, ceremonies and a feast."),
        _e(12, "A Closer Look", "A farmer finds many overlooked berries: more berries are left.",
           requires="a villager the event can be about"),
        _e(13, "The Arc of Brilliant Colors", "A villager sees a rainbow: look for its end near the mausoleum, or the cliff.",
           requires="a villager the event can be about"),
        _e(14, "The Robber Crab", "A villager spots a rare robber crab with healing properties.",
           requires="a villager the event can be about"),
        _e(15, "The Phosphorescent Fungi", "A villager finds a dangerous glowing mushroom and decides what to do.",
           requires="a villager the event can be about"),
        _e(17, "The Rainy Season", "The rainy season begins with a heavy afternoon monsoon."),
        _e(18, "The Cold Snap", "A cold, wet wind puts the village fire out.",
           requires="a lit village fire"),
        _e(20, '"A Monsoon!"', "A sudden heavy rain makes it hard to get the chores done."),
        _e(21, "The Stinging Wasps", "Wasps nest around the village and sting many villagers."),
        _e(22, "The Festival of the Banyan", "The children are celebrated for collecting their 500th mushroom.",
           requires="500 mushrooms collected and a healthy Tree of Life"),
        _e(23, "The Pure Sea Air", "Clean, pure air clears everyone's lungs."),
        _e(25, "Daredevil Barrel...of Babies! ",
           "A barrel of babies comes down the waterfalls and they join the village.",
           requires="room in the village for new villagers, and the game's own barrel conditions"),
        _e(26, "The State of the Tree", "The sickly Tree of Life makes the villagers glum and moody.",
           variant="glum", requires="the Tree of Life still in a poor state"),
        _e(27, "The State of the Tree", "The recovering Tree of Life rejuvenates the villagers.",
           variant="rejuvenated", requires="a healthy Tree of Life"),
        _e(28, "The Abandoned Infants ", "Babies are found abandoned in the bushes and the women take them in.",
           requires="the game's own condition for abandoned infants",
           variant="Female"),
        _e(29, "The Pink Shell", "A villager finds a pink shell and decides what to do with it.",
           requires="a villager the event can be about"),
        _e(30, "The Calabash Instrument", "A villager finds a notched bamboo tube: pour water into it, or not.",
           requires="a villager the event can be about"),
        _e(31, "The Climber", "A villager gets stuck at the top of the Tree of Life.",
           requires="a villager the event can be about"),
        _e(32, "The Mosquito Larvae", "Mosquito larvae in the pond: the villagers decide how to deal with them.",
           requires="a villager the event can be about, and the game's own technology conditions"),
        _e(33, "Faces in the Night", "A villager sees glowing faces in the trees: tell the tribe, or not.",
           requires="a villager the event can be about"),
        _e(34, "The Screaming Baby", "A mother with a screaming baby gets conflicting advice.",
           requires="a mother with a baby the event can be about",
           variant="Female"),
        _e(35, "The Sealed Box", "A villager finds a floating sealed box: risk swimming it back, or not.",
           requires="a villager the event can be about"),
        _e(36, "The Wet Book", "A villager finds a disintegrating book: read it now, or carry it to the lab.",
           requires="a villager the event can be about"),
        _e(37, "The Lie", "A child ate a rare mushroom instead of storing it: what to tell the adult?",
           requires="a villager the event can be about"),
        _e(38, "The Aspiring Doctor", "A gravely ill healer tries a cure: pure sea algae.",
           variant="algae", requires="a villager the event can be about"),
        _e(39, "The Aspiring Doctor", "A gravely ill healer tries a cure: sea water.",
           variant="sea water", requires="a villager the event can be about"),
        _e(40, "The Aspiring Doctor", "A gravely ill healer tries a cure: tiny amounts of forbidden mushrooms.",
           variant="mushrooms", requires="a villager the event can be about"),
        _e(41, "The Aspiring Doctor", "A gravely ill healer tries a cure: bark from the Tree of Life.",
           variant="bark", requires="a villager the event can be about"),
        _e(42, "The Aspiring Doctor", "A gravely ill healer tries a cure: a day of fasting.",
           variant="fasting", requires="a villager the event can be about"),
        _e(43, "The Aspiring Doctor", "A healer with a cut leg chooses a treatment: tree bark, or rare mushrooms.",
           variant="cut leg", requires="a villager the event can be about"),
        _e(44, "The Aspiring Scientist", "A curious villager experiments at night: white salts, or dried algae?",
           requires="a villager the event can be about"),
        _e(45, "Innovation in Construction", "A builder tests a dangerous new way to build huts.",
           requires="a villager the event can be about"),
        _e(46, "Innovation in Farming", "A villager tries to speed up cooking by sitting on the cooking pit.",
           requires="a villager the event can be about, and the game's own technology condition"),
        _e(47, "Tough Lessons", "A child is stuck high in the Tree of Life: rescue them, or let them learn.",
           requires="a child and an adult the event can be about"),
        _e(48, "The Pretty Shell", "Two children fight over a shell: teach them to share, or decide who keeps it.",
           requires="an adult the event can be about, and at least two adults"),
        _e(49, "The Legendary Stranger", "Biggles appears by the Tree of Life and answers one question.",
           requires="a villager the event can be about"),
    ],
    "vv5": [
        _e(1, "The Creeping Mold", "A toxic mold spreads in the food bin: some food is ruined."),
        _e(2, "The Allergy Season", "Many villagers suffer a bout of hay fever."),
        _e(3, "Isola Day Celebration", "The villagers celebrate their arrival on Isola with feasts."),
        _e(4, "Day of Honor", "The villagers pay their respects to those who have passed on.",
           requires="at least two graves"),
        _e(5, "The Vision", "A villager sees a stranger at the forest's edge and gains faith.",
           requires="a villager the event can be about"),
        _e(6, "The Mysterious Footprints", "Footprints appear overnight, and honeycombs: the village gains food.",
           variant="food gained"),
        _e(7, "The Mysterious Footprints", "Footprints appear overnight, and food is stolen.",
           variant="food lost"),
        _e(8, "The Mysterious Footprints", "Footprints appear overnight, and useful instruments: tech points gained.",
           variant="tech gained"),
        _e(9, "The Mysterious Footprints", "Footprints appear overnight, and research tools are stolen.",
           variant="tech lost"),
        _e(10, "Blessings Day Celebration", "The villagers give thanks with dancing, ceremonies and a feast."),
        _e(11, "The Bed Bugs", "A villager wakes up covered in bites and decides what to do about bed bugs.",
           requires="a villager the event can be about"),
        _e(12, "The Mask", "A villager finds a heathen mask: put it on, or not.",
           requires="a villager the event can be about"),
        _e(13, "The Heathen Toy", "A child finds a heathen child's toy: keep it, or return it.",
           requires="a child the event can be about"),
        _e(14, "The Daredevil Jump", "A villager wants to jump off the bridge tethered by vines.",
           requires="a villager the event can be about"),
        _e(15, "The Cold Snap", "A cold, wet wind puts the village fire out.",
           requires="a lit village fire"),
        _e(16, "Army Ants!", "Army ants devour the crops.",
           requires="the game's own progress condition for crop events"),
        _e(17, "Aphid Infestation!", "Aphids ruin much of the food.",
           requires="the game's own progress condition for crop events"),
        _e(18, "The Strange Crystals", "Green crystals found where lightning struck: the tribe gains tech points."),
        _e(19, "The Especially Offensive Cloud", "A heathen experiment fills the village with foul gas: everyone hides."),
        _e(20, "The Bottle of Spicy Juice", "A bottle of hot sauce ends up in the food, with uncomfortable results."),
        _e(21, "The River Breaks Its Banks", "A flood leaves fertile silt over the crops.",
           requires="the game's own progress condition for crop events"),
        _e(22, "The Clumsy Heathen", "A heathen spills a potion on the noni bush, which then bears more fruit."),
        _e(23, "The Pesky Critter", "A noisy lemur distracts the researchers: tech points lost.",
           requires="the game's own progress condition for the lab"),
        _e(24, "Mushroom Day!", "The villagers celebrate mushrooms, with cake for the children.",
           requires="a child the event can be about"),
        _e(25, "The Stinging Wasps", "Wasps nest around the village and sting many villagers.",
           requires=NEVER),
        _e(26, "Barrel O' Babies!", "A barrel of babies floats down the stream and the believers adopt them.",
           variant="believers", requires="room in the village for new villagers"),
        _e(27, "Barrel O' Babies!", "A barrel of babies floats down the stream and the heathens adopt them.",
           variant="heathens", requires="room in the village for new villagers"),
        _e(28, "The Salty Air", "A salty wind forces the villagers to hide until it settles."),
        _e(30, "Chutes Without Ladders", "Toddlers shoot out of the bushes into the hot springs and join the tribe.",
           requires="room in the village for new villagers"),
        _e(31, "News From Another Tribe", "A respected master from another tribe joins the village.",
           variant="a newcomer", requires="room in the village for a new villager"),
        _e(32, "News From Another Tribe", "A message from another village: the tribe gains tech points.",
           variant="a message"),
        _e(33, "The Abandoned Infants", "Babies are found abandoned in the bushes and the women take them in.",
           requires=NEVER + "; it needs room in the village for new villagers"),
        _e(34, "The Spa", "A villager sneaks into the heathens' five pools.",
           requires="a villager the event can be about"),
        _e(35, "Doubt", "A villager doubts the Guiding Hand and demands a sign.",
           requires="a villager the event can be about"),
        _e(36, "Spying on the Heathens", "A child spies on the heathens and gets caught.",
           requires="a child the event can be about"),
        _e(37, "You're Doing It Wrong!", "A villager sees the heathens trashing the lab: step in, or not.",
           requires="a villager the event can be about"),
        _e(38, "The Missing Kids", "A child is missing and a heathen is suspected.",
           requires="a child the event can be about"),
        _e(39, "Outreach?", "A heathen envoy asks for a tour of the believers' camp.",
           requires="a villager the event can be about"),
        _e(40, "The Advanced Artifacts", "A researcher finds ancient artifacts: investigate alone, or with help.",
           requires="the game's own progress condition for the artifacts"),
        _e(41, "Trick Or Trade", "The heathens have valuable scrolls: trade for them, or trick them.",
           requires="at least 100 food"),
        _e(42, "The Migrating Fruit Bats", "Fruit bats stop on their migration: scare them away, or study them.",
           requires="a villager the event can be about"),
        _e(43, "The Aphids in the Noni Bush", "Bugs are sucking the life out of the crops: deal with them wisely.",
           requires="a villager the event can be about"),
        _e(44, "The Defector", "A heathen asks to join the believers: accept, or refuse.",
           requires="a heathen the event can be about"),
        _e(45, "The Straw Hat", "A villager finds a woven reed thing: a hat, or a strainer?",
           requires="a villager the event can be about"),
        _e(46, "The Strange Nectar", "A villager finds a rare blossom full of sweet nectar.",
           requires="a villager the event can be about"),
        _e(47, "The Cracked Mask", "A heathen's mask is broken: help glue it, or not.",
           requires="a villager the event can be about"),
        _e(55, "Innovation in Farming", "A mysterious storyteller from the older parts of the island appears.",
           variant="the mysterious storyteller",
           requires="a child the event can be about, and the game's own progress condition"),
    ],
}

# Events whose code or text exists in the executable but that the game can
# never run.  Never offered.
EXCLUDED: dict[str, list[dict]] = {
    # A New Home's A Mighty Storm (island case 1) and The Furry Food
    # (encounter variant 5) never run in the original game (their condition
    # class always re-rolls), but their code and strings are complete and
    # proven to run: they are offered (see EVENTS and docs/story-cheat-upgrades.md).
    "vv1": [],
    "vv2": [
        {"title": "(case 4 of 0x433600)",
         "reason": "no event body: both tables point it at the shared epilogue / a never-valid entry "
                   "(with Restore Missing Island Events it holds the three lore pages, offered as "
                   "their own entries)"},
    ],
    "vv3": [
        {"title": "The Swarm of Bees",
         "reason": "strings only (ids 765/766): no event object and no slot in the registry"},
        {"title": "The Drought--completely wrong",
         "reason": "strings only (ids 934-937): no event object and no slot in the registry"},
    ],
    "vv4": [
        {"title": "The Tsunami", "reason": "slot 1: condition 0x4146E0 always returns false, and it is "
         "half-finished: its text says structures are destroyed but its apply never touches one (it only "
         "removes villagers, skipping the death a drowning takes)"},
        {"title": "The Medical Emergency", "reason": "slot 16: condition 0x4146E0 always returns false and "
         "never picks the villager the event is about, so no popup opens and its apply reads a null villager"},
        {"title": "The Salty Air", "reason": "slot 19: strings only, no event object"},
        {"title": "The Return of Biggles", "reason": "slot 24: condition 0x4146E0 always returns false and "
         "never picks the villager the event is about, so no popup opens and its apply reads a null villager"},
    ],
    "vv5": [
        {"title": "The Return of Biggles", "reason": "slot 29: condition 0x415B10 always returns false "
         "and never picks the villager the event is about; its apply reads a null villager"},
        {"title": "The Smelly Vial", "reason": "slot 48: condition 0x415B10 always returns false and "
         "never picks the villager the event is about; its apply reads a null villager"},
        {"title": "The Floral Vial", "reason": "slot 49: condition 0x415B10 always returns false and "
         "never picks the villager the event is about; its apply reads a null villager"},
        {"title": "The Invisible Vial", "reason": "slot 50: condition 0x415B10 always returns false and "
         "never picks the villager the event is about; its apply reads a null villager"},
        {"title": "Innovation in Farming", "reason": "slot 51: condition 0x415B10 always returns false and "
         "never picks the villager the event is about; its apply reads a null villager"},
        {"title": "Tough Lessons", "reason": "slot 52: condition 0x415B10 always returns false and "
         "never picks the villager the event is about; its apply reads a null villager"},
        {"title": "The Pretty Shell", "reason": "slot 53: condition 0x415B10 always returns false and "
         "never picks the villager the event is about; its apply reads a null villager"},
        {"title": "The Legendary Stranger", "reason": "slot 54: condition 0x415B10 always returns false and "
         "never picks the villager the event is about; its apply reads a null villager"},
        {"title": "The Tsunami, The Canoe from the Other Side, The Rainy Season, "
                  "The Festival of the Banyan, Daredevil Barrel...Of Babies!, "
                  "The State of the Tree, A Closer Look",
         "reason": "strings only: no event class and no slot in the event table"},
    ],
}
